/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.kafang.atgo.memory.avro.record;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class MarketData extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 7715243788941969675L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"MarketData\",\"namespace\":\"com.kafang.atgo.memory.avro.record\",\"fields\":[{\"name\":\"sendingTime\",\"type\":\"long\"},{\"name\":\"instrumentId\",\"type\":\"int\"},{\"name\":\"transactTime\",\"type\":\"long\"},{\"name\":\"tradingSessionId\",\"type\":\"int\"},{\"name\":\"totalVolumeTraded\",\"type\":\"long\"},{\"name\":\"totalAmtTraded\",\"type\":\"double\"},{\"name\":\"openPrice\",\"type\":\"double\"},{\"name\":\"highPrice\",\"type\":\"double\"},{\"name\":\"lowPrice\",\"type\":\"double\"},{\"name\":\"lastPrice\",\"type\":\"double\"},{\"name\":\"ask1\",\"type\":{\"type\":\"record\",\"name\":\"MdEntry\",\"fields\":[{\"name\":\"price\",\"type\":\"double\"},{\"name\":\"volume\",\"type\":\"long\"},{\"name\":\"level\",\"type\":\"int\"}]}},{\"name\":\"ask2\",\"type\":\"MdEntry\"},{\"name\":\"ask3\",\"type\":\"MdEntry\"},{\"name\":\"ask4\",\"type\":\"MdEntry\"},{\"name\":\"ask5\",\"type\":\"MdEntry\"},{\"name\":\"bid1\",\"type\":\"MdEntry\"},{\"name\":\"bid2\",\"type\":\"MdEntry\"},{\"name\":\"bid3\",\"type\":\"MdEntry\"},{\"name\":\"bid4\",\"type\":\"MdEntry\"},{\"name\":\"bid5\",\"type\":\"MdEntry\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<MarketData> ENCODER =
      new BinaryMessageEncoder<MarketData>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<MarketData> DECODER =
      new BinaryMessageDecoder<MarketData>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<MarketData> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<MarketData> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<MarketData>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this MarketData to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a MarketData from a ByteBuffer. */
  public static MarketData fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private long sendingTime;
   private int instrumentId;
   private long transactTime;
   private int tradingSessionId;
   private long totalVolumeTraded;
   private double totalAmtTraded;
   private double openPrice;
   private double highPrice;
   private double lowPrice;
   private double lastPrice;
   private com.kafang.atgo.memory.avro.record.MdEntry ask1;
   private com.kafang.atgo.memory.avro.record.MdEntry ask2;
   private com.kafang.atgo.memory.avro.record.MdEntry ask3;
   private com.kafang.atgo.memory.avro.record.MdEntry ask4;
   private com.kafang.atgo.memory.avro.record.MdEntry ask5;
   private com.kafang.atgo.memory.avro.record.MdEntry bid1;
   private com.kafang.atgo.memory.avro.record.MdEntry bid2;
   private com.kafang.atgo.memory.avro.record.MdEntry bid3;
   private com.kafang.atgo.memory.avro.record.MdEntry bid4;
   private com.kafang.atgo.memory.avro.record.MdEntry bid5;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public MarketData() {}

  /**
   * All-args constructor.
   * @param sendingTime The new value for sendingTime
   * @param instrumentId The new value for instrumentId
   * @param transactTime The new value for transactTime
   * @param tradingSessionId The new value for tradingSessionId
   * @param totalVolumeTraded The new value for totalVolumeTraded
   * @param totalAmtTraded The new value for totalAmtTraded
   * @param openPrice The new value for openPrice
   * @param highPrice The new value for highPrice
   * @param lowPrice The new value for lowPrice
   * @param lastPrice The new value for lastPrice
   * @param ask1 The new value for ask1
   * @param ask2 The new value for ask2
   * @param ask3 The new value for ask3
   * @param ask4 The new value for ask4
   * @param ask5 The new value for ask5
   * @param bid1 The new value for bid1
   * @param bid2 The new value for bid2
   * @param bid3 The new value for bid3
   * @param bid4 The new value for bid4
   * @param bid5 The new value for bid5
   */
  public MarketData(java.lang.Long sendingTime, java.lang.Integer instrumentId, java.lang.Long transactTime, java.lang.Integer tradingSessionId, java.lang.Long totalVolumeTraded, java.lang.Double totalAmtTraded, java.lang.Double openPrice, java.lang.Double highPrice, java.lang.Double lowPrice, java.lang.Double lastPrice, com.kafang.atgo.memory.avro.record.MdEntry ask1, com.kafang.atgo.memory.avro.record.MdEntry ask2, com.kafang.atgo.memory.avro.record.MdEntry ask3, com.kafang.atgo.memory.avro.record.MdEntry ask4, com.kafang.atgo.memory.avro.record.MdEntry ask5, com.kafang.atgo.memory.avro.record.MdEntry bid1, com.kafang.atgo.memory.avro.record.MdEntry bid2, com.kafang.atgo.memory.avro.record.MdEntry bid3, com.kafang.atgo.memory.avro.record.MdEntry bid4, com.kafang.atgo.memory.avro.record.MdEntry bid5) {
    this.sendingTime = sendingTime;
    this.instrumentId = instrumentId;
    this.transactTime = transactTime;
    this.tradingSessionId = tradingSessionId;
    this.totalVolumeTraded = totalVolumeTraded;
    this.totalAmtTraded = totalAmtTraded;
    this.openPrice = openPrice;
    this.highPrice = highPrice;
    this.lowPrice = lowPrice;
    this.lastPrice = lastPrice;
    this.ask1 = ask1;
    this.ask2 = ask2;
    this.ask3 = ask3;
    this.ask4 = ask4;
    this.ask5 = ask5;
    this.bid1 = bid1;
    this.bid2 = bid2;
    this.bid3 = bid3;
    this.bid4 = bid4;
    this.bid5 = bid5;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return sendingTime;
    case 1: return instrumentId;
    case 2: return transactTime;
    case 3: return tradingSessionId;
    case 4: return totalVolumeTraded;
    case 5: return totalAmtTraded;
    case 6: return openPrice;
    case 7: return highPrice;
    case 8: return lowPrice;
    case 9: return lastPrice;
    case 10: return ask1;
    case 11: return ask2;
    case 12: return ask3;
    case 13: return ask4;
    case 14: return ask5;
    case 15: return bid1;
    case 16: return bid2;
    case 17: return bid3;
    case 18: return bid4;
    case 19: return bid5;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: sendingTime = (java.lang.Long)value$; break;
    case 1: instrumentId = (java.lang.Integer)value$; break;
    case 2: transactTime = (java.lang.Long)value$; break;
    case 3: tradingSessionId = (java.lang.Integer)value$; break;
    case 4: totalVolumeTraded = (java.lang.Long)value$; break;
    case 5: totalAmtTraded = (java.lang.Double)value$; break;
    case 6: openPrice = (java.lang.Double)value$; break;
    case 7: highPrice = (java.lang.Double)value$; break;
    case 8: lowPrice = (java.lang.Double)value$; break;
    case 9: lastPrice = (java.lang.Double)value$; break;
    case 10: ask1 = (com.kafang.atgo.memory.avro.record.MdEntry)value$; break;
    case 11: ask2 = (com.kafang.atgo.memory.avro.record.MdEntry)value$; break;
    case 12: ask3 = (com.kafang.atgo.memory.avro.record.MdEntry)value$; break;
    case 13: ask4 = (com.kafang.atgo.memory.avro.record.MdEntry)value$; break;
    case 14: ask5 = (com.kafang.atgo.memory.avro.record.MdEntry)value$; break;
    case 15: bid1 = (com.kafang.atgo.memory.avro.record.MdEntry)value$; break;
    case 16: bid2 = (com.kafang.atgo.memory.avro.record.MdEntry)value$; break;
    case 17: bid3 = (com.kafang.atgo.memory.avro.record.MdEntry)value$; break;
    case 18: bid4 = (com.kafang.atgo.memory.avro.record.MdEntry)value$; break;
    case 19: bid5 = (com.kafang.atgo.memory.avro.record.MdEntry)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'sendingTime' field.
   * @return The value of the 'sendingTime' field.
   */
  public java.lang.Long getSendingTime() {
    return sendingTime;
  }

  /**
   * Sets the value of the 'sendingTime' field.
   * @param value the value to set.
   */
  public com.kafang.atgo.memory.avro.record.MarketData setSendingTime(java.lang.Long value) {
    this.sendingTime = value;
	return this;
  }

  /**
   * Gets the value of the 'instrumentId' field.
   * @return The value of the 'instrumentId' field.
   */
  public java.lang.Integer getInstrumentId() {
    return instrumentId;
  }

  /**
   * Sets the value of the 'instrumentId' field.
   * @param value the value to set.
   */
  public com.kafang.atgo.memory.avro.record.MarketData setInstrumentId(java.lang.Integer value) {
    this.instrumentId = value;
	return this;
  }

  /**
   * Gets the value of the 'transactTime' field.
   * @return The value of the 'transactTime' field.
   */
  public java.lang.Long getTransactTime() {
    return transactTime;
  }

  /**
   * Sets the value of the 'transactTime' field.
   * @param value the value to set.
   */
  public com.kafang.atgo.memory.avro.record.MarketData setTransactTime(java.lang.Long value) {
    this.transactTime = value;
	return this;
  }

  /**
   * Gets the value of the 'tradingSessionId' field.
   * @return The value of the 'tradingSessionId' field.
   */
  public java.lang.Integer getTradingSessionId() {
    return tradingSessionId;
  }

  /**
   * Sets the value of the 'tradingSessionId' field.
   * @param value the value to set.
   */
  public com.kafang.atgo.memory.avro.record.MarketData setTradingSessionId(java.lang.Integer value) {
    this.tradingSessionId = value;
	return this;
  }

  /**
   * Gets the value of the 'totalVolumeTraded' field.
   * @return The value of the 'totalVolumeTraded' field.
   */
  public java.lang.Long getTotalVolumeTraded() {
    return totalVolumeTraded;
  }

  /**
   * Sets the value of the 'totalVolumeTraded' field.
   * @param value the value to set.
   */
  public com.kafang.atgo.memory.avro.record.MarketData setTotalVolumeTraded(java.lang.Long value) {
    this.totalVolumeTraded = value;
	return this;
  }

  /**
   * Gets the value of the 'totalAmtTraded' field.
   * @return The value of the 'totalAmtTraded' field.
   */
  public java.lang.Double getTotalAmtTraded() {
    return totalAmtTraded;
  }

  /**
   * Sets the value of the 'totalAmtTraded' field.
   * @param value the value to set.
   */
  public com.kafang.atgo.memory.avro.record.MarketData setTotalAmtTraded(java.lang.Double value) {
    this.totalAmtTraded = value;
	return this;
  }

  /**
   * Gets the value of the 'openPrice' field.
   * @return The value of the 'openPrice' field.
   */
  public java.lang.Double getOpenPrice() {
    return openPrice;
  }

  /**
   * Sets the value of the 'openPrice' field.
   * @param value the value to set.
   */
  public com.kafang.atgo.memory.avro.record.MarketData setOpenPrice(java.lang.Double value) {
    this.openPrice = value;
	return this;
  }

  /**
   * Gets the value of the 'highPrice' field.
   * @return The value of the 'highPrice' field.
   */
  public java.lang.Double getHighPrice() {
    return highPrice;
  }

  /**
   * Sets the value of the 'highPrice' field.
   * @param value the value to set.
   */
  public com.kafang.atgo.memory.avro.record.MarketData setHighPrice(java.lang.Double value) {
    this.highPrice = value;
	return this;
  }

  /**
   * Gets the value of the 'lowPrice' field.
   * @return The value of the 'lowPrice' field.
   */
  public java.lang.Double getLowPrice() {
    return lowPrice;
  }

  /**
   * Sets the value of the 'lowPrice' field.
   * @param value the value to set.
   */
  public com.kafang.atgo.memory.avro.record.MarketData setLowPrice(java.lang.Double value) {
    this.lowPrice = value;
	return this;
  }

  /**
   * Gets the value of the 'lastPrice' field.
   * @return The value of the 'lastPrice' field.
   */
  public java.lang.Double getLastPrice() {
    return lastPrice;
  }

  /**
   * Sets the value of the 'lastPrice' field.
   * @param value the value to set.
   */
  public com.kafang.atgo.memory.avro.record.MarketData setLastPrice(java.lang.Double value) {
    this.lastPrice = value;
	return this;
  }

  /**
   * Gets the value of the 'ask1' field.
   * @return The value of the 'ask1' field.
   */
  public com.kafang.atgo.memory.avro.record.MdEntry getAsk1() {
    return ask1;
  }

  /**
   * Sets the value of the 'ask1' field.
   * @param value the value to set.
   */
  public com.kafang.atgo.memory.avro.record.MarketData setAsk1(com.kafang.atgo.memory.avro.record.MdEntry value) {
    this.ask1 = value;
	return this;
  }

  /**
   * Gets the value of the 'ask2' field.
   * @return The value of the 'ask2' field.
   */
  public com.kafang.atgo.memory.avro.record.MdEntry getAsk2() {
    return ask2;
  }

  /**
   * Sets the value of the 'ask2' field.
   * @param value the value to set.
   */
  public com.kafang.atgo.memory.avro.record.MarketData setAsk2(com.kafang.atgo.memory.avro.record.MdEntry value) {
    this.ask2 = value;
	return this;
  }

  /**
   * Gets the value of the 'ask3' field.
   * @return The value of the 'ask3' field.
   */
  public com.kafang.atgo.memory.avro.record.MdEntry getAsk3() {
    return ask3;
  }

  /**
   * Sets the value of the 'ask3' field.
   * @param value the value to set.
   */
  public com.kafang.atgo.memory.avro.record.MarketData setAsk3(com.kafang.atgo.memory.avro.record.MdEntry value) {
    this.ask3 = value;
	return this;
  }

  /**
   * Gets the value of the 'ask4' field.
   * @return The value of the 'ask4' field.
   */
  public com.kafang.atgo.memory.avro.record.MdEntry getAsk4() {
    return ask4;
  }

  /**
   * Sets the value of the 'ask4' field.
   * @param value the value to set.
   */
  public com.kafang.atgo.memory.avro.record.MarketData setAsk4(com.kafang.atgo.memory.avro.record.MdEntry value) {
    this.ask4 = value;
	return this;
  }

  /**
   * Gets the value of the 'ask5' field.
   * @return The value of the 'ask5' field.
   */
  public com.kafang.atgo.memory.avro.record.MdEntry getAsk5() {
    return ask5;
  }

  /**
   * Sets the value of the 'ask5' field.
   * @param value the value to set.
   */
  public com.kafang.atgo.memory.avro.record.MarketData setAsk5(com.kafang.atgo.memory.avro.record.MdEntry value) {
    this.ask5 = value;
	return this;
  }

  /**
   * Gets the value of the 'bid1' field.
   * @return The value of the 'bid1' field.
   */
  public com.kafang.atgo.memory.avro.record.MdEntry getBid1() {
    return bid1;
  }

  /**
   * Sets the value of the 'bid1' field.
   * @param value the value to set.
   */
  public com.kafang.atgo.memory.avro.record.MarketData setBid1(com.kafang.atgo.memory.avro.record.MdEntry value) {
    this.bid1 = value;
	return this;
  }

  /**
   * Gets the value of the 'bid2' field.
   * @return The value of the 'bid2' field.
   */
  public com.kafang.atgo.memory.avro.record.MdEntry getBid2() {
    return bid2;
  }

  /**
   * Sets the value of the 'bid2' field.
   * @param value the value to set.
   */
  public com.kafang.atgo.memory.avro.record.MarketData setBid2(com.kafang.atgo.memory.avro.record.MdEntry value) {
    this.bid2 = value;
	return this;
  }

  /**
   * Gets the value of the 'bid3' field.
   * @return The value of the 'bid3' field.
   */
  public com.kafang.atgo.memory.avro.record.MdEntry getBid3() {
    return bid3;
  }

  /**
   * Sets the value of the 'bid3' field.
   * @param value the value to set.
   */
  public com.kafang.atgo.memory.avro.record.MarketData setBid3(com.kafang.atgo.memory.avro.record.MdEntry value) {
    this.bid3 = value;
	return this;
  }

  /**
   * Gets the value of the 'bid4' field.
   * @return The value of the 'bid4' field.
   */
  public com.kafang.atgo.memory.avro.record.MdEntry getBid4() {
    return bid4;
  }

  /**
   * Sets the value of the 'bid4' field.
   * @param value the value to set.
   */
  public com.kafang.atgo.memory.avro.record.MarketData setBid4(com.kafang.atgo.memory.avro.record.MdEntry value) {
    this.bid4 = value;
	return this;
  }

  /**
   * Gets the value of the 'bid5' field.
   * @return The value of the 'bid5' field.
   */
  public com.kafang.atgo.memory.avro.record.MdEntry getBid5() {
    return bid5;
  }

  /**
   * Sets the value of the 'bid5' field.
   * @param value the value to set.
   */
  public com.kafang.atgo.memory.avro.record.MarketData setBid5(com.kafang.atgo.memory.avro.record.MdEntry value) {
    this.bid5 = value;
	return this;
  }

  /**
   * Creates a new MarketData RecordBuilder.
   * @return A new MarketData RecordBuilder
   */
  public static com.kafang.atgo.memory.avro.record.MarketData.Builder newBuilder() {
    return new com.kafang.atgo.memory.avro.record.MarketData.Builder();
  }

  /**
   * Creates a new MarketData RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new MarketData RecordBuilder
   */
  public static com.kafang.atgo.memory.avro.record.MarketData.Builder newBuilder(com.kafang.atgo.memory.avro.record.MarketData.Builder other) {
    return new com.kafang.atgo.memory.avro.record.MarketData.Builder(other);
  }

  /**
   * Creates a new MarketData RecordBuilder by copying an existing MarketData instance.
   * @param other The existing instance to copy.
   * @return A new MarketData RecordBuilder
   */
  public static com.kafang.atgo.memory.avro.record.MarketData.Builder newBuilder(com.kafang.atgo.memory.avro.record.MarketData other) {
    return new com.kafang.atgo.memory.avro.record.MarketData.Builder(other);
  }

  /**
   * RecordBuilder for MarketData instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<MarketData>
    implements org.apache.avro.data.RecordBuilder<MarketData> {

    private long sendingTime;
    private int instrumentId;
    private long transactTime;
    private int tradingSessionId;
    private long totalVolumeTraded;
    private double totalAmtTraded;
    private double openPrice;
    private double highPrice;
    private double lowPrice;
    private double lastPrice;
    private com.kafang.atgo.memory.avro.record.MdEntry ask1;
    private com.kafang.atgo.memory.avro.record.MdEntry.Builder ask1Builder;
    private com.kafang.atgo.memory.avro.record.MdEntry ask2;
    private com.kafang.atgo.memory.avro.record.MdEntry.Builder ask2Builder;
    private com.kafang.atgo.memory.avro.record.MdEntry ask3;
    private com.kafang.atgo.memory.avro.record.MdEntry.Builder ask3Builder;
    private com.kafang.atgo.memory.avro.record.MdEntry ask4;
    private com.kafang.atgo.memory.avro.record.MdEntry.Builder ask4Builder;
    private com.kafang.atgo.memory.avro.record.MdEntry ask5;
    private com.kafang.atgo.memory.avro.record.MdEntry.Builder ask5Builder;
    private com.kafang.atgo.memory.avro.record.MdEntry bid1;
    private com.kafang.atgo.memory.avro.record.MdEntry.Builder bid1Builder;
    private com.kafang.atgo.memory.avro.record.MdEntry bid2;
    private com.kafang.atgo.memory.avro.record.MdEntry.Builder bid2Builder;
    private com.kafang.atgo.memory.avro.record.MdEntry bid3;
    private com.kafang.atgo.memory.avro.record.MdEntry.Builder bid3Builder;
    private com.kafang.atgo.memory.avro.record.MdEntry bid4;
    private com.kafang.atgo.memory.avro.record.MdEntry.Builder bid4Builder;
    private com.kafang.atgo.memory.avro.record.MdEntry bid5;
    private com.kafang.atgo.memory.avro.record.MdEntry.Builder bid5Builder;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.kafang.atgo.memory.avro.record.MarketData.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.sendingTime)) {
        this.sendingTime = data().deepCopy(fields()[0].schema(), other.sendingTime);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.instrumentId)) {
        this.instrumentId = data().deepCopy(fields()[1].schema(), other.instrumentId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.transactTime)) {
        this.transactTime = data().deepCopy(fields()[2].schema(), other.transactTime);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.tradingSessionId)) {
        this.tradingSessionId = data().deepCopy(fields()[3].schema(), other.tradingSessionId);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.totalVolumeTraded)) {
        this.totalVolumeTraded = data().deepCopy(fields()[4].schema(), other.totalVolumeTraded);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.totalAmtTraded)) {
        this.totalAmtTraded = data().deepCopy(fields()[5].schema(), other.totalAmtTraded);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.openPrice)) {
        this.openPrice = data().deepCopy(fields()[6].schema(), other.openPrice);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.highPrice)) {
        this.highPrice = data().deepCopy(fields()[7].schema(), other.highPrice);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.lowPrice)) {
        this.lowPrice = data().deepCopy(fields()[8].schema(), other.lowPrice);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.lastPrice)) {
        this.lastPrice = data().deepCopy(fields()[9].schema(), other.lastPrice);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.ask1)) {
        this.ask1 = data().deepCopy(fields()[10].schema(), other.ask1);
        fieldSetFlags()[10] = true;
      }
      if (other.hasAsk1Builder()) {
        this.ask1Builder = com.kafang.atgo.memory.avro.record.MdEntry.newBuilder(other.getAsk1Builder());
      }
      if (isValidValue(fields()[11], other.ask2)) {
        this.ask2 = data().deepCopy(fields()[11].schema(), other.ask2);
        fieldSetFlags()[11] = true;
      }
      if (other.hasAsk2Builder()) {
        this.ask2Builder = com.kafang.atgo.memory.avro.record.MdEntry.newBuilder(other.getAsk2Builder());
      }
      if (isValidValue(fields()[12], other.ask3)) {
        this.ask3 = data().deepCopy(fields()[12].schema(), other.ask3);
        fieldSetFlags()[12] = true;
      }
      if (other.hasAsk3Builder()) {
        this.ask3Builder = com.kafang.atgo.memory.avro.record.MdEntry.newBuilder(other.getAsk3Builder());
      }
      if (isValidValue(fields()[13], other.ask4)) {
        this.ask4 = data().deepCopy(fields()[13].schema(), other.ask4);
        fieldSetFlags()[13] = true;
      }
      if (other.hasAsk4Builder()) {
        this.ask4Builder = com.kafang.atgo.memory.avro.record.MdEntry.newBuilder(other.getAsk4Builder());
      }
      if (isValidValue(fields()[14], other.ask5)) {
        this.ask5 = data().deepCopy(fields()[14].schema(), other.ask5);
        fieldSetFlags()[14] = true;
      }
      if (other.hasAsk5Builder()) {
        this.ask5Builder = com.kafang.atgo.memory.avro.record.MdEntry.newBuilder(other.getAsk5Builder());
      }
      if (isValidValue(fields()[15], other.bid1)) {
        this.bid1 = data().deepCopy(fields()[15].schema(), other.bid1);
        fieldSetFlags()[15] = true;
      }
      if (other.hasBid1Builder()) {
        this.bid1Builder = com.kafang.atgo.memory.avro.record.MdEntry.newBuilder(other.getBid1Builder());
      }
      if (isValidValue(fields()[16], other.bid2)) {
        this.bid2 = data().deepCopy(fields()[16].schema(), other.bid2);
        fieldSetFlags()[16] = true;
      }
      if (other.hasBid2Builder()) {
        this.bid2Builder = com.kafang.atgo.memory.avro.record.MdEntry.newBuilder(other.getBid2Builder());
      }
      if (isValidValue(fields()[17], other.bid3)) {
        this.bid3 = data().deepCopy(fields()[17].schema(), other.bid3);
        fieldSetFlags()[17] = true;
      }
      if (other.hasBid3Builder()) {
        this.bid3Builder = com.kafang.atgo.memory.avro.record.MdEntry.newBuilder(other.getBid3Builder());
      }
      if (isValidValue(fields()[18], other.bid4)) {
        this.bid4 = data().deepCopy(fields()[18].schema(), other.bid4);
        fieldSetFlags()[18] = true;
      }
      if (other.hasBid4Builder()) {
        this.bid4Builder = com.kafang.atgo.memory.avro.record.MdEntry.newBuilder(other.getBid4Builder());
      }
      if (isValidValue(fields()[19], other.bid5)) {
        this.bid5 = data().deepCopy(fields()[19].schema(), other.bid5);
        fieldSetFlags()[19] = true;
      }
      if (other.hasBid5Builder()) {
        this.bid5Builder = com.kafang.atgo.memory.avro.record.MdEntry.newBuilder(other.getBid5Builder());
      }
    }

    /**
     * Creates a Builder by copying an existing MarketData instance
     * @param other The existing instance to copy.
     */
    private Builder(com.kafang.atgo.memory.avro.record.MarketData other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.sendingTime)) {
        this.sendingTime = data().deepCopy(fields()[0].schema(), other.sendingTime);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.instrumentId)) {
        this.instrumentId = data().deepCopy(fields()[1].schema(), other.instrumentId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.transactTime)) {
        this.transactTime = data().deepCopy(fields()[2].schema(), other.transactTime);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.tradingSessionId)) {
        this.tradingSessionId = data().deepCopy(fields()[3].schema(), other.tradingSessionId);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.totalVolumeTraded)) {
        this.totalVolumeTraded = data().deepCopy(fields()[4].schema(), other.totalVolumeTraded);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.totalAmtTraded)) {
        this.totalAmtTraded = data().deepCopy(fields()[5].schema(), other.totalAmtTraded);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.openPrice)) {
        this.openPrice = data().deepCopy(fields()[6].schema(), other.openPrice);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.highPrice)) {
        this.highPrice = data().deepCopy(fields()[7].schema(), other.highPrice);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.lowPrice)) {
        this.lowPrice = data().deepCopy(fields()[8].schema(), other.lowPrice);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.lastPrice)) {
        this.lastPrice = data().deepCopy(fields()[9].schema(), other.lastPrice);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.ask1)) {
        this.ask1 = data().deepCopy(fields()[10].schema(), other.ask1);
        fieldSetFlags()[10] = true;
      }
      this.ask1Builder = null;
      if (isValidValue(fields()[11], other.ask2)) {
        this.ask2 = data().deepCopy(fields()[11].schema(), other.ask2);
        fieldSetFlags()[11] = true;
      }
      this.ask2Builder = null;
      if (isValidValue(fields()[12], other.ask3)) {
        this.ask3 = data().deepCopy(fields()[12].schema(), other.ask3);
        fieldSetFlags()[12] = true;
      }
      this.ask3Builder = null;
      if (isValidValue(fields()[13], other.ask4)) {
        this.ask4 = data().deepCopy(fields()[13].schema(), other.ask4);
        fieldSetFlags()[13] = true;
      }
      this.ask4Builder = null;
      if (isValidValue(fields()[14], other.ask5)) {
        this.ask5 = data().deepCopy(fields()[14].schema(), other.ask5);
        fieldSetFlags()[14] = true;
      }
      this.ask5Builder = null;
      if (isValidValue(fields()[15], other.bid1)) {
        this.bid1 = data().deepCopy(fields()[15].schema(), other.bid1);
        fieldSetFlags()[15] = true;
      }
      this.bid1Builder = null;
      if (isValidValue(fields()[16], other.bid2)) {
        this.bid2 = data().deepCopy(fields()[16].schema(), other.bid2);
        fieldSetFlags()[16] = true;
      }
      this.bid2Builder = null;
      if (isValidValue(fields()[17], other.bid3)) {
        this.bid3 = data().deepCopy(fields()[17].schema(), other.bid3);
        fieldSetFlags()[17] = true;
      }
      this.bid3Builder = null;
      if (isValidValue(fields()[18], other.bid4)) {
        this.bid4 = data().deepCopy(fields()[18].schema(), other.bid4);
        fieldSetFlags()[18] = true;
      }
      this.bid4Builder = null;
      if (isValidValue(fields()[19], other.bid5)) {
        this.bid5 = data().deepCopy(fields()[19].schema(), other.bid5);
        fieldSetFlags()[19] = true;
      }
      this.bid5Builder = null;
    }

    /**
      * Gets the value of the 'sendingTime' field.
      * @return The value.
      */
    public java.lang.Long getSendingTime() {
      return sendingTime;
    }

    /**
      * Sets the value of the 'sendingTime' field.
      * @param value The value of 'sendingTime'.
      * @return This builder.
      */
    public com.kafang.atgo.memory.avro.record.MarketData.Builder setSendingTime(long value) {
      validate(fields()[0], value);
      this.sendingTime = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'sendingTime' field has been set.
      * @return True if the 'sendingTime' field has been set, false otherwise.
      */
    public boolean hasSendingTime() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'sendingTime' field.
      * @return This builder.
      */
    public com.kafang.atgo.memory.avro.record.MarketData.Builder clearSendingTime() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'instrumentId' field.
      * @return The value.
      */
    public java.lang.Integer getInstrumentId() {
      return instrumentId;
    }

    /**
      * Sets the value of the 'instrumentId' field.
      * @param value The value of 'instrumentId'.
      * @return This builder.
      */
    public com.kafang.atgo.memory.avro.record.MarketData.Builder setInstrumentId(int value) {
      validate(fields()[1], value);
      this.instrumentId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'instrumentId' field has been set.
      * @return True if the 'instrumentId' field has been set, false otherwise.
      */
    public boolean hasInstrumentId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'instrumentId' field.
      * @return This builder.
      */
    public com.kafang.atgo.memory.avro.record.MarketData.Builder clearInstrumentId() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'transactTime' field.
      * @return The value.
      */
    public java.lang.Long getTransactTime() {
      return transactTime;
    }

    /**
      * Sets the value of the 'transactTime' field.
      * @param value The value of 'transactTime'.
      * @return This builder.
      */
    public com.kafang.atgo.memory.avro.record.MarketData.Builder setTransactTime(long value) {
      validate(fields()[2], value);
      this.transactTime = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'transactTime' field has been set.
      * @return True if the 'transactTime' field has been set, false otherwise.
      */
    public boolean hasTransactTime() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'transactTime' field.
      * @return This builder.
      */
    public com.kafang.atgo.memory.avro.record.MarketData.Builder clearTransactTime() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'tradingSessionId' field.
      * @return The value.
      */
    public java.lang.Integer getTradingSessionId() {
      return tradingSessionId;
    }

    /**
      * Sets the value of the 'tradingSessionId' field.
      * @param value The value of 'tradingSessionId'.
      * @return This builder.
      */
    public com.kafang.atgo.memory.avro.record.MarketData.Builder setTradingSessionId(int value) {
      validate(fields()[3], value);
      this.tradingSessionId = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'tradingSessionId' field has been set.
      * @return True if the 'tradingSessionId' field has been set, false otherwise.
      */
    public boolean hasTradingSessionId() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'tradingSessionId' field.
      * @return This builder.
      */
    public com.kafang.atgo.memory.avro.record.MarketData.Builder clearTradingSessionId() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'totalVolumeTraded' field.
      * @return The value.
      */
    public java.lang.Long getTotalVolumeTraded() {
      return totalVolumeTraded;
    }

    /**
      * Sets the value of the 'totalVolumeTraded' field.
      * @param value The value of 'totalVolumeTraded'.
      * @return This builder.
      */
    public com.kafang.atgo.memory.avro.record.MarketData.Builder setTotalVolumeTraded(long value) {
      validate(fields()[4], value);
      this.totalVolumeTraded = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'totalVolumeTraded' field has been set.
      * @return True if the 'totalVolumeTraded' field has been set, false otherwise.
      */
    public boolean hasTotalVolumeTraded() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'totalVolumeTraded' field.
      * @return This builder.
      */
    public com.kafang.atgo.memory.avro.record.MarketData.Builder clearTotalVolumeTraded() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'totalAmtTraded' field.
      * @return The value.
      */
    public java.lang.Double getTotalAmtTraded() {
      return totalAmtTraded;
    }

    /**
      * Sets the value of the 'totalAmtTraded' field.
      * @param value The value of 'totalAmtTraded'.
      * @return This builder.
      */
    public com.kafang.atgo.memory.avro.record.MarketData.Builder setTotalAmtTraded(double value) {
      validate(fields()[5], value);
      this.totalAmtTraded = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'totalAmtTraded' field has been set.
      * @return True if the 'totalAmtTraded' field has been set, false otherwise.
      */
    public boolean hasTotalAmtTraded() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'totalAmtTraded' field.
      * @return This builder.
      */
    public com.kafang.atgo.memory.avro.record.MarketData.Builder clearTotalAmtTraded() {
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'openPrice' field.
      * @return The value.
      */
    public java.lang.Double getOpenPrice() {
      return openPrice;
    }

    /**
      * Sets the value of the 'openPrice' field.
      * @param value The value of 'openPrice'.
      * @return This builder.
      */
    public com.kafang.atgo.memory.avro.record.MarketData.Builder setOpenPrice(double value) {
      validate(fields()[6], value);
      this.openPrice = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'openPrice' field has been set.
      * @return True if the 'openPrice' field has been set, false otherwise.
      */
    public boolean hasOpenPrice() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'openPrice' field.
      * @return This builder.
      */
    public com.kafang.atgo.memory.avro.record.MarketData.Builder clearOpenPrice() {
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'highPrice' field.
      * @return The value.
      */
    public java.lang.Double getHighPrice() {
      return highPrice;
    }

    /**
      * Sets the value of the 'highPrice' field.
      * @param value The value of 'highPrice'.
      * @return This builder.
      */
    public com.kafang.atgo.memory.avro.record.MarketData.Builder setHighPrice(double value) {
      validate(fields()[7], value);
      this.highPrice = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'highPrice' field has been set.
      * @return True if the 'highPrice' field has been set, false otherwise.
      */
    public boolean hasHighPrice() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'highPrice' field.
      * @return This builder.
      */
    public com.kafang.atgo.memory.avro.record.MarketData.Builder clearHighPrice() {
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'lowPrice' field.
      * @return The value.
      */
    public java.lang.Double getLowPrice() {
      return lowPrice;
    }

    /**
      * Sets the value of the 'lowPrice' field.
      * @param value The value of 'lowPrice'.
      * @return This builder.
      */
    public com.kafang.atgo.memory.avro.record.MarketData.Builder setLowPrice(double value) {
      validate(fields()[8], value);
      this.lowPrice = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'lowPrice' field has been set.
      * @return True if the 'lowPrice' field has been set, false otherwise.
      */
    public boolean hasLowPrice() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'lowPrice' field.
      * @return This builder.
      */
    public com.kafang.atgo.memory.avro.record.MarketData.Builder clearLowPrice() {
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'lastPrice' field.
      * @return The value.
      */
    public java.lang.Double getLastPrice() {
      return lastPrice;
    }

    /**
      * Sets the value of the 'lastPrice' field.
      * @param value The value of 'lastPrice'.
      * @return This builder.
      */
    public com.kafang.atgo.memory.avro.record.MarketData.Builder setLastPrice(double value) {
      validate(fields()[9], value);
      this.lastPrice = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'lastPrice' field has been set.
      * @return True if the 'lastPrice' field has been set, false otherwise.
      */
    public boolean hasLastPrice() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'lastPrice' field.
      * @return This builder.
      */
    public com.kafang.atgo.memory.avro.record.MarketData.Builder clearLastPrice() {
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'ask1' field.
      * @return The value.
      */
    public com.kafang.atgo.memory.avro.record.MdEntry getAsk1() {
      return ask1;
    }

    /**
      * Sets the value of the 'ask1' field.
      * @param value The value of 'ask1'.
      * @return This builder.
      */
    public com.kafang.atgo.memory.avro.record.MarketData.Builder setAsk1(com.kafang.atgo.memory.avro.record.MdEntry value) {
      validate(fields()[10], value);
      this.ask1Builder = null;
      this.ask1 = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'ask1' field has been set.
      * @return True if the 'ask1' field has been set, false otherwise.
      */
    public boolean hasAsk1() {
      return fieldSetFlags()[10];
    }

    /**
     * Gets the Builder instance for the 'ask1' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public com.kafang.atgo.memory.avro.record.MdEntry.Builder getAsk1Builder() {
      if (ask1Builder == null) {
        if (hasAsk1()) {
          setAsk1Builder(com.kafang.atgo.memory.avro.record.MdEntry.newBuilder(ask1));
        } else {
          setAsk1Builder(com.kafang.atgo.memory.avro.record.MdEntry.newBuilder());
        }
      }
      return ask1Builder;
    }

    /**
     * Sets the Builder instance for the 'ask1' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */
    public com.kafang.atgo.memory.avro.record.MarketData.Builder setAsk1Builder(com.kafang.atgo.memory.avro.record.MdEntry.Builder value) {
      clearAsk1();
      ask1Builder = value;
      return this;
    }

    /**
     * Checks whether the 'ask1' field has an active Builder instance
     * @return True if the 'ask1' field has an active Builder instance
     */
    public boolean hasAsk1Builder() {
      return ask1Builder != null;
    }

    /**
      * Clears the value of the 'ask1' field.
      * @return This builder.
      */
    public com.kafang.atgo.memory.avro.record.MarketData.Builder clearAsk1() {
      ask1 = null;
      ask1Builder = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /**
      * Gets the value of the 'ask2' field.
      * @return The value.
      */
    public com.kafang.atgo.memory.avro.record.MdEntry getAsk2() {
      return ask2;
    }

    /**
      * Sets the value of the 'ask2' field.
      * @param value The value of 'ask2'.
      * @return This builder.
      */
    public com.kafang.atgo.memory.avro.record.MarketData.Builder setAsk2(com.kafang.atgo.memory.avro.record.MdEntry value) {
      validate(fields()[11], value);
      this.ask2Builder = null;
      this.ask2 = value;
      fieldSetFlags()[11] = true;
      return this;
    }

    /**
      * Checks whether the 'ask2' field has been set.
      * @return True if the 'ask2' field has been set, false otherwise.
      */
    public boolean hasAsk2() {
      return fieldSetFlags()[11];
    }

    /**
     * Gets the Builder instance for the 'ask2' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public com.kafang.atgo.memory.avro.record.MdEntry.Builder getAsk2Builder() {
      if (ask2Builder == null) {
        if (hasAsk2()) {
          setAsk2Builder(com.kafang.atgo.memory.avro.record.MdEntry.newBuilder(ask2));
        } else {
          setAsk2Builder(com.kafang.atgo.memory.avro.record.MdEntry.newBuilder());
        }
      }
      return ask2Builder;
    }

    /**
     * Sets the Builder instance for the 'ask2' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */
    public com.kafang.atgo.memory.avro.record.MarketData.Builder setAsk2Builder(com.kafang.atgo.memory.avro.record.MdEntry.Builder value) {
      clearAsk2();
      ask2Builder = value;
      return this;
    }

    /**
     * Checks whether the 'ask2' field has an active Builder instance
     * @return True if the 'ask2' field has an active Builder instance
     */
    public boolean hasAsk2Builder() {
      return ask2Builder != null;
    }

    /**
      * Clears the value of the 'ask2' field.
      * @return This builder.
      */
    public com.kafang.atgo.memory.avro.record.MarketData.Builder clearAsk2() {
      ask2 = null;
      ask2Builder = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    /**
      * Gets the value of the 'ask3' field.
      * @return The value.
      */
    public com.kafang.atgo.memory.avro.record.MdEntry getAsk3() {
      return ask3;
    }

    /**
      * Sets the value of the 'ask3' field.
      * @param value The value of 'ask3'.
      * @return This builder.
      */
    public com.kafang.atgo.memory.avro.record.MarketData.Builder setAsk3(com.kafang.atgo.memory.avro.record.MdEntry value) {
      validate(fields()[12], value);
      this.ask3Builder = null;
      this.ask3 = value;
      fieldSetFlags()[12] = true;
      return this;
    }

    /**
      * Checks whether the 'ask3' field has been set.
      * @return True if the 'ask3' field has been set, false otherwise.
      */
    public boolean hasAsk3() {
      return fieldSetFlags()[12];
    }

    /**
     * Gets the Builder instance for the 'ask3' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public com.kafang.atgo.memory.avro.record.MdEntry.Builder getAsk3Builder() {
      if (ask3Builder == null) {
        if (hasAsk3()) {
          setAsk3Builder(com.kafang.atgo.memory.avro.record.MdEntry.newBuilder(ask3));
        } else {
          setAsk3Builder(com.kafang.atgo.memory.avro.record.MdEntry.newBuilder());
        }
      }
      return ask3Builder;
    }

    /**
     * Sets the Builder instance for the 'ask3' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */
    public com.kafang.atgo.memory.avro.record.MarketData.Builder setAsk3Builder(com.kafang.atgo.memory.avro.record.MdEntry.Builder value) {
      clearAsk3();
      ask3Builder = value;
      return this;
    }

    /**
     * Checks whether the 'ask3' field has an active Builder instance
     * @return True if the 'ask3' field has an active Builder instance
     */
    public boolean hasAsk3Builder() {
      return ask3Builder != null;
    }

    /**
      * Clears the value of the 'ask3' field.
      * @return This builder.
      */
    public com.kafang.atgo.memory.avro.record.MarketData.Builder clearAsk3() {
      ask3 = null;
      ask3Builder = null;
      fieldSetFlags()[12] = false;
      return this;
    }

    /**
      * Gets the value of the 'ask4' field.
      * @return The value.
      */
    public com.kafang.atgo.memory.avro.record.MdEntry getAsk4() {
      return ask4;
    }

    /**
      * Sets the value of the 'ask4' field.
      * @param value The value of 'ask4'.
      * @return This builder.
      */
    public com.kafang.atgo.memory.avro.record.MarketData.Builder setAsk4(com.kafang.atgo.memory.avro.record.MdEntry value) {
      validate(fields()[13], value);
      this.ask4Builder = null;
      this.ask4 = value;
      fieldSetFlags()[13] = true;
      return this;
    }

    /**
      * Checks whether the 'ask4' field has been set.
      * @return True if the 'ask4' field has been set, false otherwise.
      */
    public boolean hasAsk4() {
      return fieldSetFlags()[13];
    }

    /**
     * Gets the Builder instance for the 'ask4' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public com.kafang.atgo.memory.avro.record.MdEntry.Builder getAsk4Builder() {
      if (ask4Builder == null) {
        if (hasAsk4()) {
          setAsk4Builder(com.kafang.atgo.memory.avro.record.MdEntry.newBuilder(ask4));
        } else {
          setAsk4Builder(com.kafang.atgo.memory.avro.record.MdEntry.newBuilder());
        }
      }
      return ask4Builder;
    }

    /**
     * Sets the Builder instance for the 'ask4' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */
    public com.kafang.atgo.memory.avro.record.MarketData.Builder setAsk4Builder(com.kafang.atgo.memory.avro.record.MdEntry.Builder value) {
      clearAsk4();
      ask4Builder = value;
      return this;
    }

    /**
     * Checks whether the 'ask4' field has an active Builder instance
     * @return True if the 'ask4' field has an active Builder instance
     */
    public boolean hasAsk4Builder() {
      return ask4Builder != null;
    }

    /**
      * Clears the value of the 'ask4' field.
      * @return This builder.
      */
    public com.kafang.atgo.memory.avro.record.MarketData.Builder clearAsk4() {
      ask4 = null;
      ask4Builder = null;
      fieldSetFlags()[13] = false;
      return this;
    }

    /**
      * Gets the value of the 'ask5' field.
      * @return The value.
      */
    public com.kafang.atgo.memory.avro.record.MdEntry getAsk5() {
      return ask5;
    }

    /**
      * Sets the value of the 'ask5' field.
      * @param value The value of 'ask5'.
      * @return This builder.
      */
    public com.kafang.atgo.memory.avro.record.MarketData.Builder setAsk5(com.kafang.atgo.memory.avro.record.MdEntry value) {
      validate(fields()[14], value);
      this.ask5Builder = null;
      this.ask5 = value;
      fieldSetFlags()[14] = true;
      return this;
    }

    /**
      * Checks whether the 'ask5' field has been set.
      * @return True if the 'ask5' field has been set, false otherwise.
      */
    public boolean hasAsk5() {
      return fieldSetFlags()[14];
    }

    /**
     * Gets the Builder instance for the 'ask5' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public com.kafang.atgo.memory.avro.record.MdEntry.Builder getAsk5Builder() {
      if (ask5Builder == null) {
        if (hasAsk5()) {
          setAsk5Builder(com.kafang.atgo.memory.avro.record.MdEntry.newBuilder(ask5));
        } else {
          setAsk5Builder(com.kafang.atgo.memory.avro.record.MdEntry.newBuilder());
        }
      }
      return ask5Builder;
    }

    /**
     * Sets the Builder instance for the 'ask5' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */
    public com.kafang.atgo.memory.avro.record.MarketData.Builder setAsk5Builder(com.kafang.atgo.memory.avro.record.MdEntry.Builder value) {
      clearAsk5();
      ask5Builder = value;
      return this;
    }

    /**
     * Checks whether the 'ask5' field has an active Builder instance
     * @return True if the 'ask5' field has an active Builder instance
     */
    public boolean hasAsk5Builder() {
      return ask5Builder != null;
    }

    /**
      * Clears the value of the 'ask5' field.
      * @return This builder.
      */
    public com.kafang.atgo.memory.avro.record.MarketData.Builder clearAsk5() {
      ask5 = null;
      ask5Builder = null;
      fieldSetFlags()[14] = false;
      return this;
    }

    /**
      * Gets the value of the 'bid1' field.
      * @return The value.
      */
    public com.kafang.atgo.memory.avro.record.MdEntry getBid1() {
      return bid1;
    }

    /**
      * Sets the value of the 'bid1' field.
      * @param value The value of 'bid1'.
      * @return This builder.
      */
    public com.kafang.atgo.memory.avro.record.MarketData.Builder setBid1(com.kafang.atgo.memory.avro.record.MdEntry value) {
      validate(fields()[15], value);
      this.bid1Builder = null;
      this.bid1 = value;
      fieldSetFlags()[15] = true;
      return this;
    }

    /**
      * Checks whether the 'bid1' field has been set.
      * @return True if the 'bid1' field has been set, false otherwise.
      */
    public boolean hasBid1() {
      return fieldSetFlags()[15];
    }

    /**
     * Gets the Builder instance for the 'bid1' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public com.kafang.atgo.memory.avro.record.MdEntry.Builder getBid1Builder() {
      if (bid1Builder == null) {
        if (hasBid1()) {
          setBid1Builder(com.kafang.atgo.memory.avro.record.MdEntry.newBuilder(bid1));
        } else {
          setBid1Builder(com.kafang.atgo.memory.avro.record.MdEntry.newBuilder());
        }
      }
      return bid1Builder;
    }

    /**
     * Sets the Builder instance for the 'bid1' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */
    public com.kafang.atgo.memory.avro.record.MarketData.Builder setBid1Builder(com.kafang.atgo.memory.avro.record.MdEntry.Builder value) {
      clearBid1();
      bid1Builder = value;
      return this;
    }

    /**
     * Checks whether the 'bid1' field has an active Builder instance
     * @return True if the 'bid1' field has an active Builder instance
     */
    public boolean hasBid1Builder() {
      return bid1Builder != null;
    }

    /**
      * Clears the value of the 'bid1' field.
      * @return This builder.
      */
    public com.kafang.atgo.memory.avro.record.MarketData.Builder clearBid1() {
      bid1 = null;
      bid1Builder = null;
      fieldSetFlags()[15] = false;
      return this;
    }

    /**
      * Gets the value of the 'bid2' field.
      * @return The value.
      */
    public com.kafang.atgo.memory.avro.record.MdEntry getBid2() {
      return bid2;
    }

    /**
      * Sets the value of the 'bid2' field.
      * @param value The value of 'bid2'.
      * @return This builder.
      */
    public com.kafang.atgo.memory.avro.record.MarketData.Builder setBid2(com.kafang.atgo.memory.avro.record.MdEntry value) {
      validate(fields()[16], value);
      this.bid2Builder = null;
      this.bid2 = value;
      fieldSetFlags()[16] = true;
      return this;
    }

    /**
      * Checks whether the 'bid2' field has been set.
      * @return True if the 'bid2' field has been set, false otherwise.
      */
    public boolean hasBid2() {
      return fieldSetFlags()[16];
    }

    /**
     * Gets the Builder instance for the 'bid2' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public com.kafang.atgo.memory.avro.record.MdEntry.Builder getBid2Builder() {
      if (bid2Builder == null) {
        if (hasBid2()) {
          setBid2Builder(com.kafang.atgo.memory.avro.record.MdEntry.newBuilder(bid2));
        } else {
          setBid2Builder(com.kafang.atgo.memory.avro.record.MdEntry.newBuilder());
        }
      }
      return bid2Builder;
    }

    /**
     * Sets the Builder instance for the 'bid2' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */
    public com.kafang.atgo.memory.avro.record.MarketData.Builder setBid2Builder(com.kafang.atgo.memory.avro.record.MdEntry.Builder value) {
      clearBid2();
      bid2Builder = value;
      return this;
    }

    /**
     * Checks whether the 'bid2' field has an active Builder instance
     * @return True if the 'bid2' field has an active Builder instance
     */
    public boolean hasBid2Builder() {
      return bid2Builder != null;
    }

    /**
      * Clears the value of the 'bid2' field.
      * @return This builder.
      */
    public com.kafang.atgo.memory.avro.record.MarketData.Builder clearBid2() {
      bid2 = null;
      bid2Builder = null;
      fieldSetFlags()[16] = false;
      return this;
    }

    /**
      * Gets the value of the 'bid3' field.
      * @return The value.
      */
    public com.kafang.atgo.memory.avro.record.MdEntry getBid3() {
      return bid3;
    }

    /**
      * Sets the value of the 'bid3' field.
      * @param value The value of 'bid3'.
      * @return This builder.
      */
    public com.kafang.atgo.memory.avro.record.MarketData.Builder setBid3(com.kafang.atgo.memory.avro.record.MdEntry value) {
      validate(fields()[17], value);
      this.bid3Builder = null;
      this.bid3 = value;
      fieldSetFlags()[17] = true;
      return this;
    }

    /**
      * Checks whether the 'bid3' field has been set.
      * @return True if the 'bid3' field has been set, false otherwise.
      */
    public boolean hasBid3() {
      return fieldSetFlags()[17];
    }

    /**
     * Gets the Builder instance for the 'bid3' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public com.kafang.atgo.memory.avro.record.MdEntry.Builder getBid3Builder() {
      if (bid3Builder == null) {
        if (hasBid3()) {
          setBid3Builder(com.kafang.atgo.memory.avro.record.MdEntry.newBuilder(bid3));
        } else {
          setBid3Builder(com.kafang.atgo.memory.avro.record.MdEntry.newBuilder());
        }
      }
      return bid3Builder;
    }

    /**
     * Sets the Builder instance for the 'bid3' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */
    public com.kafang.atgo.memory.avro.record.MarketData.Builder setBid3Builder(com.kafang.atgo.memory.avro.record.MdEntry.Builder value) {
      clearBid3();
      bid3Builder = value;
      return this;
    }

    /**
     * Checks whether the 'bid3' field has an active Builder instance
     * @return True if the 'bid3' field has an active Builder instance
     */
    public boolean hasBid3Builder() {
      return bid3Builder != null;
    }

    /**
      * Clears the value of the 'bid3' field.
      * @return This builder.
      */
    public com.kafang.atgo.memory.avro.record.MarketData.Builder clearBid3() {
      bid3 = null;
      bid3Builder = null;
      fieldSetFlags()[17] = false;
      return this;
    }

    /**
      * Gets the value of the 'bid4' field.
      * @return The value.
      */
    public com.kafang.atgo.memory.avro.record.MdEntry getBid4() {
      return bid4;
    }

    /**
      * Sets the value of the 'bid4' field.
      * @param value The value of 'bid4'.
      * @return This builder.
      */
    public com.kafang.atgo.memory.avro.record.MarketData.Builder setBid4(com.kafang.atgo.memory.avro.record.MdEntry value) {
      validate(fields()[18], value);
      this.bid4Builder = null;
      this.bid4 = value;
      fieldSetFlags()[18] = true;
      return this;
    }

    /**
      * Checks whether the 'bid4' field has been set.
      * @return True if the 'bid4' field has been set, false otherwise.
      */
    public boolean hasBid4() {
      return fieldSetFlags()[18];
    }

    /**
     * Gets the Builder instance for the 'bid4' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public com.kafang.atgo.memory.avro.record.MdEntry.Builder getBid4Builder() {
      if (bid4Builder == null) {
        if (hasBid4()) {
          setBid4Builder(com.kafang.atgo.memory.avro.record.MdEntry.newBuilder(bid4));
        } else {
          setBid4Builder(com.kafang.atgo.memory.avro.record.MdEntry.newBuilder());
        }
      }
      return bid4Builder;
    }

    /**
     * Sets the Builder instance for the 'bid4' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */
    public com.kafang.atgo.memory.avro.record.MarketData.Builder setBid4Builder(com.kafang.atgo.memory.avro.record.MdEntry.Builder value) {
      clearBid4();
      bid4Builder = value;
      return this;
    }

    /**
     * Checks whether the 'bid4' field has an active Builder instance
     * @return True if the 'bid4' field has an active Builder instance
     */
    public boolean hasBid4Builder() {
      return bid4Builder != null;
    }

    /**
      * Clears the value of the 'bid4' field.
      * @return This builder.
      */
    public com.kafang.atgo.memory.avro.record.MarketData.Builder clearBid4() {
      bid4 = null;
      bid4Builder = null;
      fieldSetFlags()[18] = false;
      return this;
    }

    /**
      * Gets the value of the 'bid5' field.
      * @return The value.
      */
    public com.kafang.atgo.memory.avro.record.MdEntry getBid5() {
      return bid5;
    }

    /**
      * Sets the value of the 'bid5' field.
      * @param value The value of 'bid5'.
      * @return This builder.
      */
    public com.kafang.atgo.memory.avro.record.MarketData.Builder setBid5(com.kafang.atgo.memory.avro.record.MdEntry value) {
      validate(fields()[19], value);
      this.bid5Builder = null;
      this.bid5 = value;
      fieldSetFlags()[19] = true;
      return this;
    }

    /**
      * Checks whether the 'bid5' field has been set.
      * @return True if the 'bid5' field has been set, false otherwise.
      */
    public boolean hasBid5() {
      return fieldSetFlags()[19];
    }

    /**
     * Gets the Builder instance for the 'bid5' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public com.kafang.atgo.memory.avro.record.MdEntry.Builder getBid5Builder() {
      if (bid5Builder == null) {
        if (hasBid5()) {
          setBid5Builder(com.kafang.atgo.memory.avro.record.MdEntry.newBuilder(bid5));
        } else {
          setBid5Builder(com.kafang.atgo.memory.avro.record.MdEntry.newBuilder());
        }
      }
      return bid5Builder;
    }

    /**
     * Sets the Builder instance for the 'bid5' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */
    public com.kafang.atgo.memory.avro.record.MarketData.Builder setBid5Builder(com.kafang.atgo.memory.avro.record.MdEntry.Builder value) {
      clearBid5();
      bid5Builder = value;
      return this;
    }

    /**
     * Checks whether the 'bid5' field has an active Builder instance
     * @return True if the 'bid5' field has an active Builder instance
     */
    public boolean hasBid5Builder() {
      return bid5Builder != null;
    }

    /**
      * Clears the value of the 'bid5' field.
      * @return This builder.
      */
    public com.kafang.atgo.memory.avro.record.MarketData.Builder clearBid5() {
      bid5 = null;
      bid5Builder = null;
      fieldSetFlags()[19] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public MarketData build() {
      try {
        MarketData record = new MarketData();
        record.sendingTime = fieldSetFlags()[0] ? this.sendingTime : (java.lang.Long) defaultValue(fields()[0]);
        record.instrumentId = fieldSetFlags()[1] ? this.instrumentId : (java.lang.Integer) defaultValue(fields()[1]);
        record.transactTime = fieldSetFlags()[2] ? this.transactTime : (java.lang.Long) defaultValue(fields()[2]);
        record.tradingSessionId = fieldSetFlags()[3] ? this.tradingSessionId : (java.lang.Integer) defaultValue(fields()[3]);
        record.totalVolumeTraded = fieldSetFlags()[4] ? this.totalVolumeTraded : (java.lang.Long) defaultValue(fields()[4]);
        record.totalAmtTraded = fieldSetFlags()[5] ? this.totalAmtTraded : (java.lang.Double) defaultValue(fields()[5]);
        record.openPrice = fieldSetFlags()[6] ? this.openPrice : (java.lang.Double) defaultValue(fields()[6]);
        record.highPrice = fieldSetFlags()[7] ? this.highPrice : (java.lang.Double) defaultValue(fields()[7]);
        record.lowPrice = fieldSetFlags()[8] ? this.lowPrice : (java.lang.Double) defaultValue(fields()[8]);
        record.lastPrice = fieldSetFlags()[9] ? this.lastPrice : (java.lang.Double) defaultValue(fields()[9]);
        if (ask1Builder != null) {
          record.ask1 = this.ask1Builder.build();
        } else {
          record.ask1 = fieldSetFlags()[10] ? this.ask1 : (com.kafang.atgo.memory.avro.record.MdEntry) defaultValue(fields()[10]);
        }
        if (ask2Builder != null) {
          record.ask2 = this.ask2Builder.build();
        } else {
          record.ask2 = fieldSetFlags()[11] ? this.ask2 : (com.kafang.atgo.memory.avro.record.MdEntry) defaultValue(fields()[11]);
        }
        if (ask3Builder != null) {
          record.ask3 = this.ask3Builder.build();
        } else {
          record.ask3 = fieldSetFlags()[12] ? this.ask3 : (com.kafang.atgo.memory.avro.record.MdEntry) defaultValue(fields()[12]);
        }
        if (ask4Builder != null) {
          record.ask4 = this.ask4Builder.build();
        } else {
          record.ask4 = fieldSetFlags()[13] ? this.ask4 : (com.kafang.atgo.memory.avro.record.MdEntry) defaultValue(fields()[13]);
        }
        if (ask5Builder != null) {
          record.ask5 = this.ask5Builder.build();
        } else {
          record.ask5 = fieldSetFlags()[14] ? this.ask5 : (com.kafang.atgo.memory.avro.record.MdEntry) defaultValue(fields()[14]);
        }
        if (bid1Builder != null) {
          record.bid1 = this.bid1Builder.build();
        } else {
          record.bid1 = fieldSetFlags()[15] ? this.bid1 : (com.kafang.atgo.memory.avro.record.MdEntry) defaultValue(fields()[15]);
        }
        if (bid2Builder != null) {
          record.bid2 = this.bid2Builder.build();
        } else {
          record.bid2 = fieldSetFlags()[16] ? this.bid2 : (com.kafang.atgo.memory.avro.record.MdEntry) defaultValue(fields()[16]);
        }
        if (bid3Builder != null) {
          record.bid3 = this.bid3Builder.build();
        } else {
          record.bid3 = fieldSetFlags()[17] ? this.bid3 : (com.kafang.atgo.memory.avro.record.MdEntry) defaultValue(fields()[17]);
        }
        if (bid4Builder != null) {
          record.bid4 = this.bid4Builder.build();
        } else {
          record.bid4 = fieldSetFlags()[18] ? this.bid4 : (com.kafang.atgo.memory.avro.record.MdEntry) defaultValue(fields()[18]);
        }
        if (bid5Builder != null) {
          record.bid5 = this.bid5Builder.build();
        } else {
          record.bid5 = fieldSetFlags()[19] ? this.bid5 : (com.kafang.atgo.memory.avro.record.MdEntry) defaultValue(fields()[19]);
        }
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<MarketData>
    WRITER$ = (org.apache.avro.io.DatumWriter<MarketData>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<MarketData>
    READER$ = (org.apache.avro.io.DatumReader<MarketData>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
