-- Script generated by MySQL Compare 1.0.1.4 on 2018/9/27 15:57:55

SET @ORIGINAL_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @ORIGINAL_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @ORIGINAL_SQL_MODE=@@SQL_MODE, SQL_MODE='ALLOW_INVALID_DATES,NO_AUTO_VALUE_ON_ZERO,NO_AUTO_CREATE_USER';

SET @ORIGINAL_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @ORIGINAL_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @ORIGINAL_SQL_MODE=@@SQL_MODE, SQL_MODE='ALLOW_INVALID_DATES,NO_AUTO_VALUE_ON_ZERO,NO_AUTO_CREATE_USER';

DROP TABLE IF EXISTS `AG_ACCOUNT`;
CREATE TABLE `AG_ACCOUNT` (
  `ID` bigint(20) NOT NULL auto_increment,
  `AccountID` int(11) NOT NULL DEFAULT '0',
  `IsActive` tinyint(1) NOT NULL,
  `ClientID` int(11) NULL,
  `StrategyID` int(11) NULL,
  `EnableBalance` double NULL,
  `CreditBalance` double NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `unique_account`(`AccountID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

DROP TABLE IF EXISTS `AG_CLIENT`;
CREATE TABLE `AG_CLIENT` (
  `ID` int(11) NOT NULL auto_increment,
  `ClientID` int(11) NULL,
  `ClientName` varchar(255) NULL,
  `Broker` varchar(255) NULL,
  `IsCredit` int(11) NULL,
  `AdaptorType` varchar(255) NULL,
  `AdaptorUser1` varchar(255) NULL,
  `AdaptorUser2` varchar(255) NULL,
  `AdaptorUser3` varchar(255) NULL,
  `AdaptorPwd1` varchar(255) NULL,
  `AdaptorPwd2` varchar(255) NULL,
  `AdaptorPwd3` varchar(255) NULL,
  `CustomerID` int(11) NULL,
  UNIQUE KEY `ClientID`(`ClientID`),
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

DROP TABLE IF EXISTS `AG_CUSTOMER`;
CREATE TABLE `AG_CUSTOMER` (
  `ID` int(11) NOT NULL auto_increment,
  `CustomerID` int(11) NULL,
  `CustomerName` varchar(255) NULL,
  UNIQUE KEY `CustomerID`(`CustomerID`),
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

DROP TABLE IF EXISTS `AG_STRATEGY`;
CREATE TABLE `AG_STRATEGY` (
  `ID` int(11) NOT NULL auto_increment,
  `StrategyID` int(11) NULL,
  `StrategyName` varchar(255) NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `uniq`(`StrategyID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

DROP TABLE IF EXISTS `AG_STRATEGY_PARAM_L1`;
CREATE TABLE `AG_STRATEGY_PARAM_L1` (
  `ID` int(11) NOT NULL auto_increment,
  `AccountID` int(11) NULL,
  `Name` varchar(255) NULL,
  `Type` int(11) NULL,
  `Value` varchar(255) NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

DROP TABLE IF EXISTS `AG_STRATEGY_PARAM_L2`;
CREATE TABLE `AG_STRATEGY_PARAM_L2` (
  `ID` int(11) NOT NULL auto_increment,
  `StrategyID` int(11) NULL,
  `CustomerID` int(11) NULL,
  `Name` varchar(255) NULL,
  `Type` int(11) NULL,
  `Value` varchar(255) NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;


DROP TABLE IF EXISTS `AG_STRATEGY_PARAM_L3`;
CREATE TABLE `AG_STRATEGY_PARAM_L3` (
  `ID` int(11) NOT NULL auto_increment,
  `StrategyID` int(11) NULL,
  `Name` varchar(255) NULL,
  `Type` int(11) NULL,
  `Value` varchar(255) NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

DROP TABLE IF EXISTS `BAK_MESSAGE`;
CREATE TABLE `BAK_MESSAGE` (
  `ID` bigint(20) NOT NULL auto_increment,
  `ReceivedDate` int(11) NOT NULL,
  `ReceivedTime` int(11) NOT NULL,
  `MsgType` varchar(2) NOT NULL,
  `MsgText` mediumtext NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

DROP TABLE IF EXISTS `MSGD_ACTL`;
CREATE TABLE `MSGD_ACTL` (
  `ClOrdID` varchar(50) NOT NULL DEFAULT '',
  `ClientID` int(11) NOT NULL DEFAULT '0',
  `Account` varchar(10) NULL,
  `QuoteID` int(11) NULL,
  `Symbol` int(11) NULL,
  `SecurityType` int(11) NULL,
  `SecurityExchange` int(11) NULL,
  `Side` int(11) NULL,
  `TransactTime` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `OrderQty` int(11) NULL,
  `OrdType` int(11) NULL,
  `Price` double NULL,
  `Text` varchar(200) NULL,
  PRIMARY KEY (`ClOrdID`,`ClientID`,`TransactTime`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

DROP TABLE IF EXISTS `MSGD_ALGO`;
CREATE TABLE `MSGD_ALGO` (
  `ClOrdID` varchar(50) NOT NULL DEFAULT '',
  `ClientID` int(11) NOT NULL DEFAULT '0',
  `Account` varchar(10) NULL,
  `Symbol` int(11) NULL,
  `SecurityType` int(11) NULL,
  `SecurityExchange` int(11) NULL,
  `Side` int(11) NULL,
  `TransactTime` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `OrderQty` int(11) NULL,
  `OrdType` int(11) NULL,
  `Price` double NULL,
  `EffectiveTime` datetime NULL,
  `ExpireTime` datetime NULL,
  `LimitAction` int(11) NULL,
  `AfterAction` int(11) NULL,
  `Text` varchar(200) NULL,
  PRIMARY KEY (`ClOrdID`,`ClientID`,`TransactTime`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

DROP TABLE IF EXISTS `REC_EODORD`;
CREATE TABLE `REC_EODORD` (
  `ClOrdID` varchar(50) NOT NULL DEFAULT '',
  `ClientID` int(11) NOT NULL DEFAULT '0',
  `Symbol` int(11) NULL,
  `SecurityType` int(11) NULL,
  `SecurityExchange` int(11) NULL,
  `Side` int(11) NULL,
  `TransactTime` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `OrderQty` int(11) NULL,
  `OrdType` int(11) NULL,
  `Price` double NULL,
  `OrderID` varchar(50) NULL,
  `CumQty` int(11) NULL,
  `LeavesQty` int(11) NULL,
  `AvgPx` double NULL,
  `OrdStatus` varchar(20) NULL,
  PRIMARY KEY (`ClientID`,`ClOrdID`,`TransactTime`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

DROP TABLE IF EXISTS `REC_SODPOS`;
CREATE TABLE `REC_SODPOS` (
  `ClientID` int(11) NOT NULL DEFAULT '0',
  `TransactTime` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `Symbol` int(11) NOT NULL DEFAULT '0',
  `SecurityType` int(11) NULL,
  `SecurityExchange` int(11) NULL,
  `currentQty` int(11) NULL,
  `tradableQty` int(11) NULL,
  `shortQty` int(11) NULL,
  PRIMARY KEY (`ClientID`,`Symbol`,`TransactTime`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

DROP TABLE IF EXISTS `RPT_ACTUAL`;
CREATE TABLE `RPT_ACTUAL` (
  `ID` int(11) NOT NULL auto_increment,
  `AsOfDate` date NULL,
  `CustomerID` int(11) NULL,
  `CustomerName` varchar(200) NULL,
  `ClientID` int(11) NULL,
  `ClientName` varchar(200) NULL,
  `StrategyID` int(11) NULL,
  `StrategyName` varchar(200) NULL,
  `AccountID` int(11) NULL,
  `QuoteID` varchar(200) NULL,
  `ClOrdID` varchar(200) NULL,
  `OrderID` varchar(200) NULL,
  `Symbol` int(11) NULL,
  `SecurityType` int(11) NULL,
  `SecurityExchange` int(11) NULL,
  `Side` char(1) NULL,
  `OrderTime` int(11) NULL,
  `OrderQty` int(11) NULL,
  `OrdType` int(11) NULL,
  `Price` double NULL,
  `CumQty` int(11) NULL,
  `CanceledQty` int(11) NULL,
  `AvgPx` double NULL,
  `Fee` double NULL,
  PRIMARY KEY (`ID`),
  KEY `index_name`(`AsOfDate`, `CustomerID`, `StrategyID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

DROP TABLE IF EXISTS `RPT_NOMINAL`;
CREATE TABLE `RPT_NOMINAL` (
  `ID` int(11) NOT NULL auto_increment,
  `AsOfDate` date NULL,
  `CustomerID` int(11) NULL,
  `CustomerName` varchar(200) NULL,
  `ClientID` int(11) NULL,
  `ClientName` varchar(200) NULL,
  `StrategyID` int(11) NULL,
  `StrategyName` varchar(200) NULL,
  `AccountID` int(11) NULL,
  `QuoteID` varchar(200) NULL,
  `Symbol` int(11) NULL,
  `SecurityType` int(11) NULL,
  `SecurityExchange` int(11) NULL,
  `StartTime` int(11) NULL,
  `EndTime` int(11) NULL,
  `DeliverTime` int(20) NULL,
  `CancelTime` int(20) NULL,
  `TaskQty` int(11) NULL,
  `CancelQty` int(11) NULL,
  `BenchmarkType` varchar(200) NULL,
  `TWAP` double NULL,
  `VWAP` double NULL,
  `ArrivalPrice` double NULL,
  `ClosePrice` double NULL,
  `FilledQtyAgg` int(11) NULL,
  `DifQtyAgg` int(11) NULL,
  `FilledPriceAgg` double NULL,
  `OrderCountAgg` int(11) NULL,
  `CanceledCountAgg` int(11) NULL,
  `FeeAgg` double NULL,
  `MarketStatus` int(11) NULL,
  PRIMARY KEY (`ID`),
  KEY `index_name`(`AsOfDate`, `CustomerID`, `StrategyID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;


DROP TABLE IF EXISTS `RPT_STRATEGY`;
CREATE TABLE `RPT_STRATEGY` (
  `ID` int(11) NOT NULL auto_increment,
  `AsOfDate` date NULL,
  `CustomerID` int(11) NULL,
  `CustomerName` varchar(200) NULL,
  `ClientID` int(11) NULL,
  `ClientName` varchar(200) NULL,
  `StrategyID` int(11) NULL,
  `StrategyName` varchar(200) NULL,
  `AccountID` int(11) NULL,
  `TaskMcap` double NULL,
  `FilledMcap` double NULL,
  `OverMcap` double NULL,
  `UnderMcap` double NULL,
  `CancelRatio` double NULL,
  `PnLLiq` decimal(10,0) NULL,
  `PnLBPS` double NULL,
  `PnLYuan` double NULL,
  PRIMARY KEY (`ID`),
  KEY `index_name`(`AsOfDate`, `CustomerID`, `StrategyID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;


DROP TABLE IF EXISTS `SIM_STRATEGY_PARAM_HIST`;
CREATE TABLE `SIM_STRATEGY_PARAM_HIST` (
  `ID` int(11) NOT NULL auto_increment,
  `StrategyID` int(11) NULL,
  `CustomerID` int(11) NULL,
  `ClientID` int(11) NULL,
  `AccountID` int(11) NULL,
  `UseTime` datetime NULL,
  `Name` varchar(255) NULL,
  `Type` int(11) NULL,
  `Value` varchar(255) NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;


DROP TABLE IF EXISTS `Student_Test`;
CREATE TABLE `Student_Test` (
  `ID` bigint(20) NOT NULL auto_increment,
  `SName` varchar(255) NULL,
  `SAge` int(11) NULL,
  `SSex` tinyint(1) NULL,
  `aaa` varchar(255) NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;


DROP TABLE IF EXISTS `WS_AUDITTRAIL`;
CREATE TABLE `WS_AUDITTRAIL` (
  `id` bigint(20) NOT NULL auto_increment,
  `username` varchar(255) NULL,
  `opType` varchar(50) NULL,
  `describe` varchar(10000) NULL,
  `time` datetime NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;


DROP TABLE IF EXISTS `WS_HARDWARE`;
CREATE TABLE `WS_HARDWARE` (
  `id` bigint(20) NOT NULL auto_increment,
  `userId` int(11) NULL,
  `mac` varchar(255) NULL,
  `iip` varchar(255) NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;


DROP TABLE IF EXISTS `WS_ORDER_INS`;
CREATE TABLE `WS_ORDER_INS` (
  `id` bigint(20) NOT NULL auto_increment,
  `isReview` int(50) NULL,
  `EffectiveTime` datetime NULL,
  `ExpireTime` datetime NULL,
  `limitAction` varchar(255) NULL,
  `afterAction` varchar(255) NULL,
  `ClOrdID` varchar(50) NULL,
  `ClientID` varchar(255) NULL,
  `AccountID` varchar(10) NULL,
  `Symbol` bigint(20) NULL,
  `SecurityType` varchar(255) NULL,
  `SecurityExchange` varchar(255) NULL,
  `Side` varchar(255) NULL,
  `TransactTime` datetime NULL,
  `OrderQty` int(20) NULL,
  `OrdType` varchar(255) NULL,
  `Price` bigint(20) NULL,
  `reviewTime` datetime NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;


DROP TABLE IF EXISTS `WS_PHONE`;
CREATE TABLE `WS_PHONE` (
  `id` int(11) NOT NULL auto_increment,
  `phone` varchar(32) NOT NULL,
  `userId` int(10) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;


DROP TABLE IF EXISTS `WS_USER`;
CREATE TABLE `WS_USER` (
  `id` bigint(20) NOT NULL auto_increment,
  `userid` bigint(20) NOT NULL,
  `username` varchar(32) NOT NULL,
  `password` varchar(32) NOT NULL,
  `role` varchar(32) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

DROP TABLE IF EXISTS `WS_USER_CUSTOMER_MP`;
CREATE TABLE `WS_USER_CUSTOMER_MP` (
  `Id` int(11) NOT NULL auto_increment,
  `UserID` int(11) NULL,
  `CustomerID` int(11) NULL,
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

SET FOREIGN_KEY_CHECKS=@ORIGINAL_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@ORIGINAL_UNIQUE_CHECKS;
SET SQL_MODE=@ORIGINAL_SQL_MODE;