/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.kafang.atgo.memory.avro.record;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Order extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 8890662694680586390L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Order\",\"namespace\":\"com.kafang.atgo.memory.avro.record\",\"fields\":[{\"name\":\"sendingTime\",\"type\":\"long\"},{\"name\":\"transactTime\",\"type\":\"long\"},{\"name\":\"localTimestamp\",\"type\":\"long\"},{\"name\":\"clOrdId\",\"type\":\"long\"},{\"name\":\"strategyId\",\"type\":\"int\"},{\"name\":\"clientId\",\"type\":\"int\"},{\"name\":\"accountId\",\"type\":\"int\"},{\"name\":\"handlInst\",\"type\":\"int\"},{\"name\":\"quoteId\",\"type\":\"long\"},{\"name\":\"instrumentId\",\"type\":\"int\"},{\"name\":\"symbol\",\"type\":\"int\"},{\"name\":\"securityType\",\"type\":\"int\"},{\"name\":\"securityExchange\",\"type\":\"int\"},{\"name\":\"side\",\"type\":\"int\"},{\"name\":\"orderQty\",\"type\":\"int\"},{\"name\":\"ordType\",\"type\":\"int\"},{\"name\":\"price\",\"type\":\"double\"},{\"name\":\"effectiveTime\",\"type\":\"long\"},{\"name\":\"expireTime\",\"type\":\"long\"},{\"name\":\"execId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"orderId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"cumQty\",\"type\":\"int\"},{\"name\":\"leavesQty\",\"type\":\"int\"},{\"name\":\"avgPrice\",\"type\":\"double\"},{\"name\":\"ordStatus\",\"type\":\"int\"},{\"name\":\"limitAction\",\"type\":\"int\"},{\"name\":\"afterAction\",\"type\":\"int\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Order> ENCODER =
      new BinaryMessageEncoder<Order>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Order> DECODER =
      new BinaryMessageDecoder<Order>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<Order> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<Order> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Order>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this Order to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a Order from a ByteBuffer. */
  public static Order fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private long sendingTime;
   private long transactTime;
   private long localTimestamp;
   private long clOrdId;
   private int strategyId;
   private int clientId;
   private int accountId;
   private int handlInst;
   private long quoteId;
   private int instrumentId;
   private int symbol;
   private int securityType;
   private int securityExchange;
   private int side;
   private int orderQty;
   private int ordType;
   private double price;
   private long effectiveTime;
   private long expireTime;
   private java.lang.String execId;
   private java.lang.String orderId;
   private int cumQty;
   private int leavesQty;
   private double avgPrice;
   private int ordStatus;
   private int limitAction;
   private int afterAction;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Order() {}

  /**
   * All-args constructor.
   * @param sendingTime The new value for sendingTime
   * @param transactTime The new value for transactTime
   * @param localTimestamp The new value for localTimestamp
   * @param clOrdId The new value for clOrdId
   * @param strategyId The new value for strategyId
   * @param clientId The new value for clientId
   * @param accountId The new value for accountId
   * @param handlInst The new value for handlInst
   * @param quoteId The new value for quoteId
   * @param instrumentId The new value for instrumentId
   * @param symbol The new value for symbol
   * @param securityType The new value for securityType
   * @param securityExchange The new value for securityExchange
   * @param side The new value for side
   * @param orderQty The new value for orderQty
   * @param ordType The new value for ordType
   * @param price The new value for price
   * @param effectiveTime The new value for effectiveTime
   * @param expireTime The new value for expireTime
   * @param execId The new value for execId
   * @param orderId The new value for orderId
   * @param cumQty The new value for cumQty
   * @param leavesQty The new value for leavesQty
   * @param avgPrice The new value for avgPrice
   * @param ordStatus The new value for ordStatus
   * @param limitAction The new value for limitAction
   * @param afterAction The new value for afterAction
   */
  public Order(java.lang.Long sendingTime, java.lang.Long transactTime, java.lang.Long localTimestamp, java.lang.Long clOrdId, java.lang.Integer strategyId, java.lang.Integer clientId, java.lang.Integer accountId, java.lang.Integer handlInst, java.lang.Long quoteId, java.lang.Integer instrumentId, java.lang.Integer symbol, java.lang.Integer securityType, java.lang.Integer securityExchange, java.lang.Integer side, java.lang.Integer orderQty, java.lang.Integer ordType, java.lang.Double price, java.lang.Long effectiveTime, java.lang.Long expireTime, java.lang.String execId, java.lang.String orderId, java.lang.Integer cumQty, java.lang.Integer leavesQty, java.lang.Double avgPrice, java.lang.Integer ordStatus, java.lang.Integer limitAction, java.lang.Integer afterAction) {
    this.sendingTime = sendingTime;
    this.transactTime = transactTime;
    this.localTimestamp = localTimestamp;
    this.clOrdId = clOrdId;
    this.strategyId = strategyId;
    this.clientId = clientId;
    this.accountId = accountId;
    this.handlInst = handlInst;
    this.quoteId = quoteId;
    this.instrumentId = instrumentId;
    this.symbol = symbol;
    this.securityType = securityType;
    this.securityExchange = securityExchange;
    this.side = side;
    this.orderQty = orderQty;
    this.ordType = ordType;
    this.price = price;
    this.effectiveTime = effectiveTime;
    this.expireTime = expireTime;
    this.execId = execId;
    this.orderId = orderId;
    this.cumQty = cumQty;
    this.leavesQty = leavesQty;
    this.avgPrice = avgPrice;
    this.ordStatus = ordStatus;
    this.limitAction = limitAction;
    this.afterAction = afterAction;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return sendingTime;
    case 1: return transactTime;
    case 2: return localTimestamp;
    case 3: return clOrdId;
    case 4: return strategyId;
    case 5: return clientId;
    case 6: return accountId;
    case 7: return handlInst;
    case 8: return quoteId;
    case 9: return instrumentId;
    case 10: return symbol;
    case 11: return securityType;
    case 12: return securityExchange;
    case 13: return side;
    case 14: return orderQty;
    case 15: return ordType;
    case 16: return price;
    case 17: return effectiveTime;
    case 18: return expireTime;
    case 19: return execId;
    case 20: return orderId;
    case 21: return cumQty;
    case 22: return leavesQty;
    case 23: return avgPrice;
    case 24: return ordStatus;
    case 25: return limitAction;
    case 26: return afterAction;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: sendingTime = (java.lang.Long)value$; break;
    case 1: transactTime = (java.lang.Long)value$; break;
    case 2: localTimestamp = (java.lang.Long)value$; break;
    case 3: clOrdId = (java.lang.Long)value$; break;
    case 4: strategyId = (java.lang.Integer)value$; break;
    case 5: clientId = (java.lang.Integer)value$; break;
    case 6: accountId = (java.lang.Integer)value$; break;
    case 7: handlInst = (java.lang.Integer)value$; break;
    case 8: quoteId = (java.lang.Long)value$; break;
    case 9: instrumentId = (java.lang.Integer)value$; break;
    case 10: symbol = (java.lang.Integer)value$; break;
    case 11: securityType = (java.lang.Integer)value$; break;
    case 12: securityExchange = (java.lang.Integer)value$; break;
    case 13: side = (java.lang.Integer)value$; break;
    case 14: orderQty = (java.lang.Integer)value$; break;
    case 15: ordType = (java.lang.Integer)value$; break;
    case 16: price = (java.lang.Double)value$; break;
    case 17: effectiveTime = (java.lang.Long)value$; break;
    case 18: expireTime = (java.lang.Long)value$; break;
    case 19: execId = (java.lang.String)value$; break;
    case 20: orderId = (java.lang.String)value$; break;
    case 21: cumQty = (java.lang.Integer)value$; break;
    case 22: leavesQty = (java.lang.Integer)value$; break;
    case 23: avgPrice = (java.lang.Double)value$; break;
    case 24: ordStatus = (java.lang.Integer)value$; break;
    case 25: limitAction = (java.lang.Integer)value$; break;
    case 26: afterAction = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'sendingTime' field.
   * @return The value of the 'sendingTime' field.
   */
  public java.lang.Long getSendingTime() {
    return sendingTime;
  }

  /**
   * Sets the value of the 'sendingTime' field.
   * @param value the value to set.
   */
  public com.kafang.atgo.memory.avro.record.Order setSendingTime(java.lang.Long value) {
    this.sendingTime = value;
	return this;
  }

  /**
   * Gets the value of the 'transactTime' field.
   * @return The value of the 'transactTime' field.
   */
  public java.lang.Long getTransactTime() {
    return transactTime;
  }

  /**
   * Sets the value of the 'transactTime' field.
   * @param value the value to set.
   */
  public com.kafang.atgo.memory.avro.record.Order setTransactTime(java.lang.Long value) {
    this.transactTime = value;
	return this;
  }

  /**
   * Gets the value of the 'localTimestamp' field.
   * @return The value of the 'localTimestamp' field.
   */
  public java.lang.Long getLocalTimestamp() {
    return localTimestamp;
  }

  /**
   * Sets the value of the 'localTimestamp' field.
   * @param value the value to set.
   */
  public com.kafang.atgo.memory.avro.record.Order setLocalTimestamp(java.lang.Long value) {
    this.localTimestamp = value;
	return this;
  }

  /**
   * Gets the value of the 'clOrdId' field.
   * @return The value of the 'clOrdId' field.
   */
  public java.lang.Long getClOrdId() {
    return clOrdId;
  }

  /**
   * Sets the value of the 'clOrdId' field.
   * @param value the value to set.
   */
  public com.kafang.atgo.memory.avro.record.Order setClOrdId(java.lang.Long value) {
    this.clOrdId = value;
	return this;
  }

  /**
   * Gets the value of the 'strategyId' field.
   * @return The value of the 'strategyId' field.
   */
  public java.lang.Integer getStrategyId() {
    return strategyId;
  }

  /**
   * Sets the value of the 'strategyId' field.
   * @param value the value to set.
   */
  public com.kafang.atgo.memory.avro.record.Order setStrategyId(java.lang.Integer value) {
    this.strategyId = value;
	return this;
  }

  /**
   * Gets the value of the 'clientId' field.
   * @return The value of the 'clientId' field.
   */
  public java.lang.Integer getClientId() {
    return clientId;
  }

  /**
   * Sets the value of the 'clientId' field.
   * @param value the value to set.
   */
  public com.kafang.atgo.memory.avro.record.Order setClientId(java.lang.Integer value) {
    this.clientId = value;
	return this;
  }

  /**
   * Gets the value of the 'accountId' field.
   * @return The value of the 'accountId' field.
   */
  public java.lang.Integer getAccountId() {
    return accountId;
  }

  /**
   * Sets the value of the 'accountId' field.
   * @param value the value to set.
   */
  public com.kafang.atgo.memory.avro.record.Order setAccountId(java.lang.Integer value) {
    this.accountId = value;
	return this;
  }

  /**
   * Gets the value of the 'handlInst' field.
   * @return The value of the 'handlInst' field.
   */
  public java.lang.Integer getHandlInst() {
    return handlInst;
  }

  /**
   * Sets the value of the 'handlInst' field.
   * @param value the value to set.
   */
  public com.kafang.atgo.memory.avro.record.Order setHandlInst(java.lang.Integer value) {
    this.handlInst = value;
	return this;
  }

  /**
   * Gets the value of the 'quoteId' field.
   * @return The value of the 'quoteId' field.
   */
  public java.lang.Long getQuoteId() {
    return quoteId;
  }

  /**
   * Sets the value of the 'quoteId' field.
   * @param value the value to set.
   */
  public com.kafang.atgo.memory.avro.record.Order setQuoteId(java.lang.Long value) {
    this.quoteId = value;
	return this;
  }

  /**
   * Gets the value of the 'instrumentId' field.
   * @return The value of the 'instrumentId' field.
   */
  public java.lang.Integer getInstrumentId() {
    return instrumentId;
  }

  /**
   * Sets the value of the 'instrumentId' field.
   * @param value the value to set.
   */
  public com.kafang.atgo.memory.avro.record.Order setInstrumentId(java.lang.Integer value) {
    this.instrumentId = value;
	return this;
  }

  /**
   * Gets the value of the 'symbol' field.
   * @return The value of the 'symbol' field.
   */
  public java.lang.Integer getSymbol() {
    return symbol;
  }

  /**
   * Sets the value of the 'symbol' field.
   * @param value the value to set.
   */
  public com.kafang.atgo.memory.avro.record.Order setSymbol(java.lang.Integer value) {
    this.symbol = value;
	return this;
  }

  /**
   * Gets the value of the 'securityType' field.
   * @return The value of the 'securityType' field.
   */
  public java.lang.Integer getSecurityType() {
    return securityType;
  }

  /**
   * Sets the value of the 'securityType' field.
   * @param value the value to set.
   */
  public com.kafang.atgo.memory.avro.record.Order setSecurityType(java.lang.Integer value) {
    this.securityType = value;
	return this;
  }

  /**
   * Gets the value of the 'securityExchange' field.
   * @return The value of the 'securityExchange' field.
   */
  public java.lang.Integer getSecurityExchange() {
    return securityExchange;
  }

  /**
   * Sets the value of the 'securityExchange' field.
   * @param value the value to set.
   */
  public com.kafang.atgo.memory.avro.record.Order setSecurityExchange(java.lang.Integer value) {
    this.securityExchange = value;
	return this;
  }

  /**
   * Gets the value of the 'side' field.
   * @return The value of the 'side' field.
   */
  public java.lang.Integer getSide() {
    return side;
  }

  /**
   * Sets the value of the 'side' field.
   * @param value the value to set.
   */
  public com.kafang.atgo.memory.avro.record.Order setSide(java.lang.Integer value) {
    this.side = value;
	return this;
  }

  /**
   * Gets the value of the 'orderQty' field.
   * @return The value of the 'orderQty' field.
   */
  public java.lang.Integer getOrderQty() {
    return orderQty;
  }

  /**
   * Sets the value of the 'orderQty' field.
   * @param value the value to set.
   */
  public com.kafang.atgo.memory.avro.record.Order setOrderQty(java.lang.Integer value) {
    this.orderQty = value;
	return this;
  }

  /**
   * Gets the value of the 'ordType' field.
   * @return The value of the 'ordType' field.
   */
  public java.lang.Integer getOrdType() {
    return ordType;
  }

  /**
   * Sets the value of the 'ordType' field.
   * @param value the value to set.
   */
  public com.kafang.atgo.memory.avro.record.Order setOrdType(java.lang.Integer value) {
    this.ordType = value;
	return this;
  }

  /**
   * Gets the value of the 'price' field.
   * @return The value of the 'price' field.
   */
  public java.lang.Double getPrice() {
    return price;
  }

  /**
   * Sets the value of the 'price' field.
   * @param value the value to set.
   */
  public com.kafang.atgo.memory.avro.record.Order setPrice(java.lang.Double value) {
    this.price = value;
	return this;
  }

  /**
   * Gets the value of the 'effectiveTime' field.
   * @return The value of the 'effectiveTime' field.
   */
  public java.lang.Long getEffectiveTime() {
    return effectiveTime;
  }

  /**
   * Sets the value of the 'effectiveTime' field.
   * @param value the value to set.
   */
  public com.kafang.atgo.memory.avro.record.Order setEffectiveTime(java.lang.Long value) {
    this.effectiveTime = value;
	return this;
  }

  /**
   * Gets the value of the 'expireTime' field.
   * @return The value of the 'expireTime' field.
   */
  public java.lang.Long getExpireTime() {
    return expireTime;
  }

  /**
   * Sets the value of the 'expireTime' field.
   * @param value the value to set.
   */
  public com.kafang.atgo.memory.avro.record.Order setExpireTime(java.lang.Long value) {
    this.expireTime = value;
	return this;
  }

  /**
   * Gets the value of the 'execId' field.
   * @return The value of the 'execId' field.
   */
  public java.lang.String getExecId() {
    return execId;
  }

  /**
   * Sets the value of the 'execId' field.
   * @param value the value to set.
   */
  public com.kafang.atgo.memory.avro.record.Order setExecId(java.lang.String value) {
    this.execId = value;
	return this;
  }

  /**
   * Gets the value of the 'orderId' field.
   * @return The value of the 'orderId' field.
   */
  public java.lang.String getOrderId() {
    return orderId;
  }

  /**
   * Sets the value of the 'orderId' field.
   * @param value the value to set.
   */
  public com.kafang.atgo.memory.avro.record.Order setOrderId(java.lang.String value) {
    this.orderId = value;
	return this;
  }

  /**
   * Gets the value of the 'cumQty' field.
   * @return The value of the 'cumQty' field.
   */
  public java.lang.Integer getCumQty() {
    return cumQty;
  }

  /**
   * Sets the value of the 'cumQty' field.
   * @param value the value to set.
   */
  public com.kafang.atgo.memory.avro.record.Order setCumQty(java.lang.Integer value) {
    this.cumQty = value;
	return this;
  }

  /**
   * Gets the value of the 'leavesQty' field.
   * @return The value of the 'leavesQty' field.
   */
  public java.lang.Integer getLeavesQty() {
    return leavesQty;
  }

  /**
   * Sets the value of the 'leavesQty' field.
   * @param value the value to set.
   */
  public com.kafang.atgo.memory.avro.record.Order setLeavesQty(java.lang.Integer value) {
    this.leavesQty = value;
	return this;
  }

  /**
   * Gets the value of the 'avgPrice' field.
   * @return The value of the 'avgPrice' field.
   */
  public java.lang.Double getAvgPrice() {
    return avgPrice;
  }

  /**
   * Sets the value of the 'avgPrice' field.
   * @param value the value to set.
   */
  public com.kafang.atgo.memory.avro.record.Order setAvgPrice(java.lang.Double value) {
    this.avgPrice = value;
	return this;
  }

  /**
   * Gets the value of the 'ordStatus' field.
   * @return The value of the 'ordStatus' field.
   */
  public java.lang.Integer getOrdStatus() {
    return ordStatus;
  }

  /**
   * Sets the value of the 'ordStatus' field.
   * @param value the value to set.
   */
  public com.kafang.atgo.memory.avro.record.Order setOrdStatus(java.lang.Integer value) {
    this.ordStatus = value;
	return this;
  }

  /**
   * Gets the value of the 'limitAction' field.
   * @return The value of the 'limitAction' field.
   */
  public java.lang.Integer getLimitAction() {
    return limitAction;
  }

  /**
   * Sets the value of the 'limitAction' field.
   * @param value the value to set.
   */
  public com.kafang.atgo.memory.avro.record.Order setLimitAction(java.lang.Integer value) {
    this.limitAction = value;
	return this;
  }

  /**
   * Gets the value of the 'afterAction' field.
   * @return The value of the 'afterAction' field.
   */
  public java.lang.Integer getAfterAction() {
    return afterAction;
  }

  /**
   * Sets the value of the 'afterAction' field.
   * @param value the value to set.
   */
  public com.kafang.atgo.memory.avro.record.Order setAfterAction(java.lang.Integer value) {
    this.afterAction = value;
	return this;
  }

  /**
   * Creates a new Order RecordBuilder.
   * @return A new Order RecordBuilder
   */
  public static com.kafang.atgo.memory.avro.record.Order.Builder newBuilder() {
    return new com.kafang.atgo.memory.avro.record.Order.Builder();
  }

  /**
   * Creates a new Order RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Order RecordBuilder
   */
  public static com.kafang.atgo.memory.avro.record.Order.Builder newBuilder(com.kafang.atgo.memory.avro.record.Order.Builder other) {
    return new com.kafang.atgo.memory.avro.record.Order.Builder(other);
  }

  /**
   * Creates a new Order RecordBuilder by copying an existing Order instance.
   * @param other The existing instance to copy.
   * @return A new Order RecordBuilder
   */
  public static com.kafang.atgo.memory.avro.record.Order.Builder newBuilder(com.kafang.atgo.memory.avro.record.Order other) {
    return new com.kafang.atgo.memory.avro.record.Order.Builder(other);
  }

  /**
   * RecordBuilder for Order instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Order>
    implements org.apache.avro.data.RecordBuilder<Order> {

    private long sendingTime;
    private long transactTime;
    private long localTimestamp;
    private long clOrdId;
    private int strategyId;
    private int clientId;
    private int accountId;
    private int handlInst;
    private long quoteId;
    private int instrumentId;
    private int symbol;
    private int securityType;
    private int securityExchange;
    private int side;
    private int orderQty;
    private int ordType;
    private double price;
    private long effectiveTime;
    private long expireTime;
    private java.lang.String execId;
    private java.lang.String orderId;
    private int cumQty;
    private int leavesQty;
    private double avgPrice;
    private int ordStatus;
    private int limitAction;
    private int afterAction;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.kafang.atgo.memory.avro.record.Order.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.sendingTime)) {
        this.sendingTime = data().deepCopy(fields()[0].schema(), other.sendingTime);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.transactTime)) {
        this.transactTime = data().deepCopy(fields()[1].schema(), other.transactTime);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.localTimestamp)) {
        this.localTimestamp = data().deepCopy(fields()[2].schema(), other.localTimestamp);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.clOrdId)) {
        this.clOrdId = data().deepCopy(fields()[3].schema(), other.clOrdId);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.strategyId)) {
        this.strategyId = data().deepCopy(fields()[4].schema(), other.strategyId);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.clientId)) {
        this.clientId = data().deepCopy(fields()[5].schema(), other.clientId);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.accountId)) {
        this.accountId = data().deepCopy(fields()[6].schema(), other.accountId);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.handlInst)) {
        this.handlInst = data().deepCopy(fields()[7].schema(), other.handlInst);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.quoteId)) {
        this.quoteId = data().deepCopy(fields()[8].schema(), other.quoteId);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.instrumentId)) {
        this.instrumentId = data().deepCopy(fields()[9].schema(), other.instrumentId);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.symbol)) {
        this.symbol = data().deepCopy(fields()[10].schema(), other.symbol);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.securityType)) {
        this.securityType = data().deepCopy(fields()[11].schema(), other.securityType);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.securityExchange)) {
        this.securityExchange = data().deepCopy(fields()[12].schema(), other.securityExchange);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.side)) {
        this.side = data().deepCopy(fields()[13].schema(), other.side);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.orderQty)) {
        this.orderQty = data().deepCopy(fields()[14].schema(), other.orderQty);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.ordType)) {
        this.ordType = data().deepCopy(fields()[15].schema(), other.ordType);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other.price)) {
        this.price = data().deepCopy(fields()[16].schema(), other.price);
        fieldSetFlags()[16] = true;
      }
      if (isValidValue(fields()[17], other.effectiveTime)) {
        this.effectiveTime = data().deepCopy(fields()[17].schema(), other.effectiveTime);
        fieldSetFlags()[17] = true;
      }
      if (isValidValue(fields()[18], other.expireTime)) {
        this.expireTime = data().deepCopy(fields()[18].schema(), other.expireTime);
        fieldSetFlags()[18] = true;
      }
      if (isValidValue(fields()[19], other.execId)) {
        this.execId = data().deepCopy(fields()[19].schema(), other.execId);
        fieldSetFlags()[19] = true;
      }
      if (isValidValue(fields()[20], other.orderId)) {
        this.orderId = data().deepCopy(fields()[20].schema(), other.orderId);
        fieldSetFlags()[20] = true;
      }
      if (isValidValue(fields()[21], other.cumQty)) {
        this.cumQty = data().deepCopy(fields()[21].schema(), other.cumQty);
        fieldSetFlags()[21] = true;
      }
      if (isValidValue(fields()[22], other.leavesQty)) {
        this.leavesQty = data().deepCopy(fields()[22].schema(), other.leavesQty);
        fieldSetFlags()[22] = true;
      }
      if (isValidValue(fields()[23], other.avgPrice)) {
        this.avgPrice = data().deepCopy(fields()[23].schema(), other.avgPrice);
        fieldSetFlags()[23] = true;
      }
      if (isValidValue(fields()[24], other.ordStatus)) {
        this.ordStatus = data().deepCopy(fields()[24].schema(), other.ordStatus);
        fieldSetFlags()[24] = true;
      }
      if (isValidValue(fields()[25], other.limitAction)) {
        this.limitAction = data().deepCopy(fields()[25].schema(), other.limitAction);
        fieldSetFlags()[25] = true;
      }
      if (isValidValue(fields()[26], other.afterAction)) {
        this.afterAction = data().deepCopy(fields()[26].schema(), other.afterAction);
        fieldSetFlags()[26] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Order instance
     * @param other The existing instance to copy.
     */
    private Builder(com.kafang.atgo.memory.avro.record.Order other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.sendingTime)) {
        this.sendingTime = data().deepCopy(fields()[0].schema(), other.sendingTime);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.transactTime)) {
        this.transactTime = data().deepCopy(fields()[1].schema(), other.transactTime);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.localTimestamp)) {
        this.localTimestamp = data().deepCopy(fields()[2].schema(), other.localTimestamp);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.clOrdId)) {
        this.clOrdId = data().deepCopy(fields()[3].schema(), other.clOrdId);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.strategyId)) {
        this.strategyId = data().deepCopy(fields()[4].schema(), other.strategyId);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.clientId)) {
        this.clientId = data().deepCopy(fields()[5].schema(), other.clientId);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.accountId)) {
        this.accountId = data().deepCopy(fields()[6].schema(), other.accountId);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.handlInst)) {
        this.handlInst = data().deepCopy(fields()[7].schema(), other.handlInst);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.quoteId)) {
        this.quoteId = data().deepCopy(fields()[8].schema(), other.quoteId);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.instrumentId)) {
        this.instrumentId = data().deepCopy(fields()[9].schema(), other.instrumentId);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.symbol)) {
        this.symbol = data().deepCopy(fields()[10].schema(), other.symbol);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.securityType)) {
        this.securityType = data().deepCopy(fields()[11].schema(), other.securityType);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.securityExchange)) {
        this.securityExchange = data().deepCopy(fields()[12].schema(), other.securityExchange);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.side)) {
        this.side = data().deepCopy(fields()[13].schema(), other.side);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.orderQty)) {
        this.orderQty = data().deepCopy(fields()[14].schema(), other.orderQty);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.ordType)) {
        this.ordType = data().deepCopy(fields()[15].schema(), other.ordType);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other.price)) {
        this.price = data().deepCopy(fields()[16].schema(), other.price);
        fieldSetFlags()[16] = true;
      }
      if (isValidValue(fields()[17], other.effectiveTime)) {
        this.effectiveTime = data().deepCopy(fields()[17].schema(), other.effectiveTime);
        fieldSetFlags()[17] = true;
      }
      if (isValidValue(fields()[18], other.expireTime)) {
        this.expireTime = data().deepCopy(fields()[18].schema(), other.expireTime);
        fieldSetFlags()[18] = true;
      }
      if (isValidValue(fields()[19], other.execId)) {
        this.execId = data().deepCopy(fields()[19].schema(), other.execId);
        fieldSetFlags()[19] = true;
      }
      if (isValidValue(fields()[20], other.orderId)) {
        this.orderId = data().deepCopy(fields()[20].schema(), other.orderId);
        fieldSetFlags()[20] = true;
      }
      if (isValidValue(fields()[21], other.cumQty)) {
        this.cumQty = data().deepCopy(fields()[21].schema(), other.cumQty);
        fieldSetFlags()[21] = true;
      }
      if (isValidValue(fields()[22], other.leavesQty)) {
        this.leavesQty = data().deepCopy(fields()[22].schema(), other.leavesQty);
        fieldSetFlags()[22] = true;
      }
      if (isValidValue(fields()[23], other.avgPrice)) {
        this.avgPrice = data().deepCopy(fields()[23].schema(), other.avgPrice);
        fieldSetFlags()[23] = true;
      }
      if (isValidValue(fields()[24], other.ordStatus)) {
        this.ordStatus = data().deepCopy(fields()[24].schema(), other.ordStatus);
        fieldSetFlags()[24] = true;
      }
      if (isValidValue(fields()[25], other.limitAction)) {
        this.limitAction = data().deepCopy(fields()[25].schema(), other.limitAction);
        fieldSetFlags()[25] = true;
      }
      if (isValidValue(fields()[26], other.afterAction)) {
        this.afterAction = data().deepCopy(fields()[26].schema(), other.afterAction);
        fieldSetFlags()[26] = true;
      }
    }

    /**
      * Gets the value of the 'sendingTime' field.
      * @return The value.
      */
    public java.lang.Long getSendingTime() {
      return sendingTime;
    }

    /**
      * Sets the value of the 'sendingTime' field.
      * @param value The value of 'sendingTime'.
      * @return This builder.
      */
    public com.kafang.atgo.memory.avro.record.Order.Builder setSendingTime(long value) {
      validate(fields()[0], value);
      this.sendingTime = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'sendingTime' field has been set.
      * @return True if the 'sendingTime' field has been set, false otherwise.
      */
    public boolean hasSendingTime() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'sendingTime' field.
      * @return This builder.
      */
    public com.kafang.atgo.memory.avro.record.Order.Builder clearSendingTime() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'transactTime' field.
      * @return The value.
      */
    public java.lang.Long getTransactTime() {
      return transactTime;
    }

    /**
      * Sets the value of the 'transactTime' field.
      * @param value The value of 'transactTime'.
      * @return This builder.
      */
    public com.kafang.atgo.memory.avro.record.Order.Builder setTransactTime(long value) {
      validate(fields()[1], value);
      this.transactTime = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'transactTime' field has been set.
      * @return True if the 'transactTime' field has been set, false otherwise.
      */
    public boolean hasTransactTime() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'transactTime' field.
      * @return This builder.
      */
    public com.kafang.atgo.memory.avro.record.Order.Builder clearTransactTime() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'localTimestamp' field.
      * @return The value.
      */
    public java.lang.Long getLocalTimestamp() {
      return localTimestamp;
    }

    /**
      * Sets the value of the 'localTimestamp' field.
      * @param value The value of 'localTimestamp'.
      * @return This builder.
      */
    public com.kafang.atgo.memory.avro.record.Order.Builder setLocalTimestamp(long value) {
      validate(fields()[2], value);
      this.localTimestamp = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'localTimestamp' field has been set.
      * @return True if the 'localTimestamp' field has been set, false otherwise.
      */
    public boolean hasLocalTimestamp() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'localTimestamp' field.
      * @return This builder.
      */
    public com.kafang.atgo.memory.avro.record.Order.Builder clearLocalTimestamp() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'clOrdId' field.
      * @return The value.
      */
    public java.lang.Long getClOrdId() {
      return clOrdId;
    }

    /**
      * Sets the value of the 'clOrdId' field.
      * @param value The value of 'clOrdId'.
      * @return This builder.
      */
    public com.kafang.atgo.memory.avro.record.Order.Builder setClOrdId(long value) {
      validate(fields()[3], value);
      this.clOrdId = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'clOrdId' field has been set.
      * @return True if the 'clOrdId' field has been set, false otherwise.
      */
    public boolean hasClOrdId() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'clOrdId' field.
      * @return This builder.
      */
    public com.kafang.atgo.memory.avro.record.Order.Builder clearClOrdId() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'strategyId' field.
      * @return The value.
      */
    public java.lang.Integer getStrategyId() {
      return strategyId;
    }

    /**
      * Sets the value of the 'strategyId' field.
      * @param value The value of 'strategyId'.
      * @return This builder.
      */
    public com.kafang.atgo.memory.avro.record.Order.Builder setStrategyId(int value) {
      validate(fields()[4], value);
      this.strategyId = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'strategyId' field has been set.
      * @return True if the 'strategyId' field has been set, false otherwise.
      */
    public boolean hasStrategyId() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'strategyId' field.
      * @return This builder.
      */
    public com.kafang.atgo.memory.avro.record.Order.Builder clearStrategyId() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'clientId' field.
      * @return The value.
      */
    public java.lang.Integer getClientId() {
      return clientId;
    }

    /**
      * Sets the value of the 'clientId' field.
      * @param value The value of 'clientId'.
      * @return This builder.
      */
    public com.kafang.atgo.memory.avro.record.Order.Builder setClientId(int value) {
      validate(fields()[5], value);
      this.clientId = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'clientId' field has been set.
      * @return True if the 'clientId' field has been set, false otherwise.
      */
    public boolean hasClientId() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'clientId' field.
      * @return This builder.
      */
    public com.kafang.atgo.memory.avro.record.Order.Builder clearClientId() {
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'accountId' field.
      * @return The value.
      */
    public java.lang.Integer getAccountId() {
      return accountId;
    }

    /**
      * Sets the value of the 'accountId' field.
      * @param value The value of 'accountId'.
      * @return This builder.
      */
    public com.kafang.atgo.memory.avro.record.Order.Builder setAccountId(int value) {
      validate(fields()[6], value);
      this.accountId = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'accountId' field has been set.
      * @return True if the 'accountId' field has been set, false otherwise.
      */
    public boolean hasAccountId() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'accountId' field.
      * @return This builder.
      */
    public com.kafang.atgo.memory.avro.record.Order.Builder clearAccountId() {
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'handlInst' field.
      * @return The value.
      */
    public java.lang.Integer getHandlInst() {
      return handlInst;
    }

    /**
      * Sets the value of the 'handlInst' field.
      * @param value The value of 'handlInst'.
      * @return This builder.
      */
    public com.kafang.atgo.memory.avro.record.Order.Builder setHandlInst(int value) {
      validate(fields()[7], value);
      this.handlInst = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'handlInst' field has been set.
      * @return True if the 'handlInst' field has been set, false otherwise.
      */
    public boolean hasHandlInst() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'handlInst' field.
      * @return This builder.
      */
    public com.kafang.atgo.memory.avro.record.Order.Builder clearHandlInst() {
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'quoteId' field.
      * @return The value.
      */
    public java.lang.Long getQuoteId() {
      return quoteId;
    }

    /**
      * Sets the value of the 'quoteId' field.
      * @param value The value of 'quoteId'.
      * @return This builder.
      */
    public com.kafang.atgo.memory.avro.record.Order.Builder setQuoteId(long value) {
      validate(fields()[8], value);
      this.quoteId = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'quoteId' field has been set.
      * @return True if the 'quoteId' field has been set, false otherwise.
      */
    public boolean hasQuoteId() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'quoteId' field.
      * @return This builder.
      */
    public com.kafang.atgo.memory.avro.record.Order.Builder clearQuoteId() {
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'instrumentId' field.
      * @return The value.
      */
    public java.lang.Integer getInstrumentId() {
      return instrumentId;
    }

    /**
      * Sets the value of the 'instrumentId' field.
      * @param value The value of 'instrumentId'.
      * @return This builder.
      */
    public com.kafang.atgo.memory.avro.record.Order.Builder setInstrumentId(int value) {
      validate(fields()[9], value);
      this.instrumentId = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'instrumentId' field has been set.
      * @return True if the 'instrumentId' field has been set, false otherwise.
      */
    public boolean hasInstrumentId() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'instrumentId' field.
      * @return This builder.
      */
    public com.kafang.atgo.memory.avro.record.Order.Builder clearInstrumentId() {
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'symbol' field.
      * @return The value.
      */
    public java.lang.Integer getSymbol() {
      return symbol;
    }

    /**
      * Sets the value of the 'symbol' field.
      * @param value The value of 'symbol'.
      * @return This builder.
      */
    public com.kafang.atgo.memory.avro.record.Order.Builder setSymbol(int value) {
      validate(fields()[10], value);
      this.symbol = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'symbol' field has been set.
      * @return True if the 'symbol' field has been set, false otherwise.
      */
    public boolean hasSymbol() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'symbol' field.
      * @return This builder.
      */
    public com.kafang.atgo.memory.avro.record.Order.Builder clearSymbol() {
      fieldSetFlags()[10] = false;
      return this;
    }

    /**
      * Gets the value of the 'securityType' field.
      * @return The value.
      */
    public java.lang.Integer getSecurityType() {
      return securityType;
    }

    /**
      * Sets the value of the 'securityType' field.
      * @param value The value of 'securityType'.
      * @return This builder.
      */
    public com.kafang.atgo.memory.avro.record.Order.Builder setSecurityType(int value) {
      validate(fields()[11], value);
      this.securityType = value;
      fieldSetFlags()[11] = true;
      return this;
    }

    /**
      * Checks whether the 'securityType' field has been set.
      * @return True if the 'securityType' field has been set, false otherwise.
      */
    public boolean hasSecurityType() {
      return fieldSetFlags()[11];
    }


    /**
      * Clears the value of the 'securityType' field.
      * @return This builder.
      */
    public com.kafang.atgo.memory.avro.record.Order.Builder clearSecurityType() {
      fieldSetFlags()[11] = false;
      return this;
    }

    /**
      * Gets the value of the 'securityExchange' field.
      * @return The value.
      */
    public java.lang.Integer getSecurityExchange() {
      return securityExchange;
    }

    /**
      * Sets the value of the 'securityExchange' field.
      * @param value The value of 'securityExchange'.
      * @return This builder.
      */
    public com.kafang.atgo.memory.avro.record.Order.Builder setSecurityExchange(int value) {
      validate(fields()[12], value);
      this.securityExchange = value;
      fieldSetFlags()[12] = true;
      return this;
    }

    /**
      * Checks whether the 'securityExchange' field has been set.
      * @return True if the 'securityExchange' field has been set, false otherwise.
      */
    public boolean hasSecurityExchange() {
      return fieldSetFlags()[12];
    }


    /**
      * Clears the value of the 'securityExchange' field.
      * @return This builder.
      */
    public com.kafang.atgo.memory.avro.record.Order.Builder clearSecurityExchange() {
      fieldSetFlags()[12] = false;
      return this;
    }

    /**
      * Gets the value of the 'side' field.
      * @return The value.
      */
    public java.lang.Integer getSide() {
      return side;
    }

    /**
      * Sets the value of the 'side' field.
      * @param value The value of 'side'.
      * @return This builder.
      */
    public com.kafang.atgo.memory.avro.record.Order.Builder setSide(int value) {
      validate(fields()[13], value);
      this.side = value;
      fieldSetFlags()[13] = true;
      return this;
    }

    /**
      * Checks whether the 'side' field has been set.
      * @return True if the 'side' field has been set, false otherwise.
      */
    public boolean hasSide() {
      return fieldSetFlags()[13];
    }


    /**
      * Clears the value of the 'side' field.
      * @return This builder.
      */
    public com.kafang.atgo.memory.avro.record.Order.Builder clearSide() {
      fieldSetFlags()[13] = false;
      return this;
    }

    /**
      * Gets the value of the 'orderQty' field.
      * @return The value.
      */
    public java.lang.Integer getOrderQty() {
      return orderQty;
    }

    /**
      * Sets the value of the 'orderQty' field.
      * @param value The value of 'orderQty'.
      * @return This builder.
      */
    public com.kafang.atgo.memory.avro.record.Order.Builder setOrderQty(int value) {
      validate(fields()[14], value);
      this.orderQty = value;
      fieldSetFlags()[14] = true;
      return this;
    }

    /**
      * Checks whether the 'orderQty' field has been set.
      * @return True if the 'orderQty' field has been set, false otherwise.
      */
    public boolean hasOrderQty() {
      return fieldSetFlags()[14];
    }


    /**
      * Clears the value of the 'orderQty' field.
      * @return This builder.
      */
    public com.kafang.atgo.memory.avro.record.Order.Builder clearOrderQty() {
      fieldSetFlags()[14] = false;
      return this;
    }

    /**
      * Gets the value of the 'ordType' field.
      * @return The value.
      */
    public java.lang.Integer getOrdType() {
      return ordType;
    }

    /**
      * Sets the value of the 'ordType' field.
      * @param value The value of 'ordType'.
      * @return This builder.
      */
    public com.kafang.atgo.memory.avro.record.Order.Builder setOrdType(int value) {
      validate(fields()[15], value);
      this.ordType = value;
      fieldSetFlags()[15] = true;
      return this;
    }

    /**
      * Checks whether the 'ordType' field has been set.
      * @return True if the 'ordType' field has been set, false otherwise.
      */
    public boolean hasOrdType() {
      return fieldSetFlags()[15];
    }


    /**
      * Clears the value of the 'ordType' field.
      * @return This builder.
      */
    public com.kafang.atgo.memory.avro.record.Order.Builder clearOrdType() {
      fieldSetFlags()[15] = false;
      return this;
    }

    /**
      * Gets the value of the 'price' field.
      * @return The value.
      */
    public java.lang.Double getPrice() {
      return price;
    }

    /**
      * Sets the value of the 'price' field.
      * @param value The value of 'price'.
      * @return This builder.
      */
    public com.kafang.atgo.memory.avro.record.Order.Builder setPrice(double value) {
      validate(fields()[16], value);
      this.price = value;
      fieldSetFlags()[16] = true;
      return this;
    }

    /**
      * Checks whether the 'price' field has been set.
      * @return True if the 'price' field has been set, false otherwise.
      */
    public boolean hasPrice() {
      return fieldSetFlags()[16];
    }


    /**
      * Clears the value of the 'price' field.
      * @return This builder.
      */
    public com.kafang.atgo.memory.avro.record.Order.Builder clearPrice() {
      fieldSetFlags()[16] = false;
      return this;
    }

    /**
      * Gets the value of the 'effectiveTime' field.
      * @return The value.
      */
    public java.lang.Long getEffectiveTime() {
      return effectiveTime;
    }

    /**
      * Sets the value of the 'effectiveTime' field.
      * @param value The value of 'effectiveTime'.
      * @return This builder.
      */
    public com.kafang.atgo.memory.avro.record.Order.Builder setEffectiveTime(long value) {
      validate(fields()[17], value);
      this.effectiveTime = value;
      fieldSetFlags()[17] = true;
      return this;
    }

    /**
      * Checks whether the 'effectiveTime' field has been set.
      * @return True if the 'effectiveTime' field has been set, false otherwise.
      */
    public boolean hasEffectiveTime() {
      return fieldSetFlags()[17];
    }


    /**
      * Clears the value of the 'effectiveTime' field.
      * @return This builder.
      */
    public com.kafang.atgo.memory.avro.record.Order.Builder clearEffectiveTime() {
      fieldSetFlags()[17] = false;
      return this;
    }

    /**
      * Gets the value of the 'expireTime' field.
      * @return The value.
      */
    public java.lang.Long getExpireTime() {
      return expireTime;
    }

    /**
      * Sets the value of the 'expireTime' field.
      * @param value The value of 'expireTime'.
      * @return This builder.
      */
    public com.kafang.atgo.memory.avro.record.Order.Builder setExpireTime(long value) {
      validate(fields()[18], value);
      this.expireTime = value;
      fieldSetFlags()[18] = true;
      return this;
    }

    /**
      * Checks whether the 'expireTime' field has been set.
      * @return True if the 'expireTime' field has been set, false otherwise.
      */
    public boolean hasExpireTime() {
      return fieldSetFlags()[18];
    }


    /**
      * Clears the value of the 'expireTime' field.
      * @return This builder.
      */
    public com.kafang.atgo.memory.avro.record.Order.Builder clearExpireTime() {
      fieldSetFlags()[18] = false;
      return this;
    }

    /**
      * Gets the value of the 'execId' field.
      * @return The value.
      */
    public java.lang.String getExecId() {
      return execId;
    }

    /**
      * Sets the value of the 'execId' field.
      * @param value The value of 'execId'.
      * @return This builder.
      */
    public com.kafang.atgo.memory.avro.record.Order.Builder setExecId(java.lang.String value) {
      validate(fields()[19], value);
      this.execId = value;
      fieldSetFlags()[19] = true;
      return this;
    }

    /**
      * Checks whether the 'execId' field has been set.
      * @return True if the 'execId' field has been set, false otherwise.
      */
    public boolean hasExecId() {
      return fieldSetFlags()[19];
    }


    /**
      * Clears the value of the 'execId' field.
      * @return This builder.
      */
    public com.kafang.atgo.memory.avro.record.Order.Builder clearExecId() {
      execId = null;
      fieldSetFlags()[19] = false;
      return this;
    }

    /**
      * Gets the value of the 'orderId' field.
      * @return The value.
      */
    public java.lang.String getOrderId() {
      return orderId;
    }

    /**
      * Sets the value of the 'orderId' field.
      * @param value The value of 'orderId'.
      * @return This builder.
      */
    public com.kafang.atgo.memory.avro.record.Order.Builder setOrderId(java.lang.String value) {
      validate(fields()[20], value);
      this.orderId = value;
      fieldSetFlags()[20] = true;
      return this;
    }

    /**
      * Checks whether the 'orderId' field has been set.
      * @return True if the 'orderId' field has been set, false otherwise.
      */
    public boolean hasOrderId() {
      return fieldSetFlags()[20];
    }


    /**
      * Clears the value of the 'orderId' field.
      * @return This builder.
      */
    public com.kafang.atgo.memory.avro.record.Order.Builder clearOrderId() {
      orderId = null;
      fieldSetFlags()[20] = false;
      return this;
    }

    /**
      * Gets the value of the 'cumQty' field.
      * @return The value.
      */
    public java.lang.Integer getCumQty() {
      return cumQty;
    }

    /**
      * Sets the value of the 'cumQty' field.
      * @param value The value of 'cumQty'.
      * @return This builder.
      */
    public com.kafang.atgo.memory.avro.record.Order.Builder setCumQty(int value) {
      validate(fields()[21], value);
      this.cumQty = value;
      fieldSetFlags()[21] = true;
      return this;
    }

    /**
      * Checks whether the 'cumQty' field has been set.
      * @return True if the 'cumQty' field has been set, false otherwise.
      */
    public boolean hasCumQty() {
      return fieldSetFlags()[21];
    }


    /**
      * Clears the value of the 'cumQty' field.
      * @return This builder.
      */
    public com.kafang.atgo.memory.avro.record.Order.Builder clearCumQty() {
      fieldSetFlags()[21] = false;
      return this;
    }

    /**
      * Gets the value of the 'leavesQty' field.
      * @return The value.
      */
    public java.lang.Integer getLeavesQty() {
      return leavesQty;
    }

    /**
      * Sets the value of the 'leavesQty' field.
      * @param value The value of 'leavesQty'.
      * @return This builder.
      */
    public com.kafang.atgo.memory.avro.record.Order.Builder setLeavesQty(int value) {
      validate(fields()[22], value);
      this.leavesQty = value;
      fieldSetFlags()[22] = true;
      return this;
    }

    /**
      * Checks whether the 'leavesQty' field has been set.
      * @return True if the 'leavesQty' field has been set, false otherwise.
      */
    public boolean hasLeavesQty() {
      return fieldSetFlags()[22];
    }


    /**
      * Clears the value of the 'leavesQty' field.
      * @return This builder.
      */
    public com.kafang.atgo.memory.avro.record.Order.Builder clearLeavesQty() {
      fieldSetFlags()[22] = false;
      return this;
    }

    /**
      * Gets the value of the 'avgPrice' field.
      * @return The value.
      */
    public java.lang.Double getAvgPrice() {
      return avgPrice;
    }

    /**
      * Sets the value of the 'avgPrice' field.
      * @param value The value of 'avgPrice'.
      * @return This builder.
      */
    public com.kafang.atgo.memory.avro.record.Order.Builder setAvgPrice(double value) {
      validate(fields()[23], value);
      this.avgPrice = value;
      fieldSetFlags()[23] = true;
      return this;
    }

    /**
      * Checks whether the 'avgPrice' field has been set.
      * @return True if the 'avgPrice' field has been set, false otherwise.
      */
    public boolean hasAvgPrice() {
      return fieldSetFlags()[23];
    }


    /**
      * Clears the value of the 'avgPrice' field.
      * @return This builder.
      */
    public com.kafang.atgo.memory.avro.record.Order.Builder clearAvgPrice() {
      fieldSetFlags()[23] = false;
      return this;
    }

    /**
      * Gets the value of the 'ordStatus' field.
      * @return The value.
      */
    public java.lang.Integer getOrdStatus() {
      return ordStatus;
    }

    /**
      * Sets the value of the 'ordStatus' field.
      * @param value The value of 'ordStatus'.
      * @return This builder.
      */
    public com.kafang.atgo.memory.avro.record.Order.Builder setOrdStatus(int value) {
      validate(fields()[24], value);
      this.ordStatus = value;
      fieldSetFlags()[24] = true;
      return this;
    }

    /**
      * Checks whether the 'ordStatus' field has been set.
      * @return True if the 'ordStatus' field has been set, false otherwise.
      */
    public boolean hasOrdStatus() {
      return fieldSetFlags()[24];
    }


    /**
      * Clears the value of the 'ordStatus' field.
      * @return This builder.
      */
    public com.kafang.atgo.memory.avro.record.Order.Builder clearOrdStatus() {
      fieldSetFlags()[24] = false;
      return this;
    }

    /**
      * Gets the value of the 'limitAction' field.
      * @return The value.
      */
    public java.lang.Integer getLimitAction() {
      return limitAction;
    }

    /**
      * Sets the value of the 'limitAction' field.
      * @param value The value of 'limitAction'.
      * @return This builder.
      */
    public com.kafang.atgo.memory.avro.record.Order.Builder setLimitAction(int value) {
      validate(fields()[25], value);
      this.limitAction = value;
      fieldSetFlags()[25] = true;
      return this;
    }

    /**
      * Checks whether the 'limitAction' field has been set.
      * @return True if the 'limitAction' field has been set, false otherwise.
      */
    public boolean hasLimitAction() {
      return fieldSetFlags()[25];
    }


    /**
      * Clears the value of the 'limitAction' field.
      * @return This builder.
      */
    public com.kafang.atgo.memory.avro.record.Order.Builder clearLimitAction() {
      fieldSetFlags()[25] = false;
      return this;
    }

    /**
      * Gets the value of the 'afterAction' field.
      * @return The value.
      */
    public java.lang.Integer getAfterAction() {
      return afterAction;
    }

    /**
      * Sets the value of the 'afterAction' field.
      * @param value The value of 'afterAction'.
      * @return This builder.
      */
    public com.kafang.atgo.memory.avro.record.Order.Builder setAfterAction(int value) {
      validate(fields()[26], value);
      this.afterAction = value;
      fieldSetFlags()[26] = true;
      return this;
    }

    /**
      * Checks whether the 'afterAction' field has been set.
      * @return True if the 'afterAction' field has been set, false otherwise.
      */
    public boolean hasAfterAction() {
      return fieldSetFlags()[26];
    }


    /**
      * Clears the value of the 'afterAction' field.
      * @return This builder.
      */
    public com.kafang.atgo.memory.avro.record.Order.Builder clearAfterAction() {
      fieldSetFlags()[26] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Order build() {
      try {
        Order record = new Order();
        record.sendingTime = fieldSetFlags()[0] ? this.sendingTime : (java.lang.Long) defaultValue(fields()[0]);
        record.transactTime = fieldSetFlags()[1] ? this.transactTime : (java.lang.Long) defaultValue(fields()[1]);
        record.localTimestamp = fieldSetFlags()[2] ? this.localTimestamp : (java.lang.Long) defaultValue(fields()[2]);
        record.clOrdId = fieldSetFlags()[3] ? this.clOrdId : (java.lang.Long) defaultValue(fields()[3]);
        record.strategyId = fieldSetFlags()[4] ? this.strategyId : (java.lang.Integer) defaultValue(fields()[4]);
        record.clientId = fieldSetFlags()[5] ? this.clientId : (java.lang.Integer) defaultValue(fields()[5]);
        record.accountId = fieldSetFlags()[6] ? this.accountId : (java.lang.Integer) defaultValue(fields()[6]);
        record.handlInst = fieldSetFlags()[7] ? this.handlInst : (java.lang.Integer) defaultValue(fields()[7]);
        record.quoteId = fieldSetFlags()[8] ? this.quoteId : (java.lang.Long) defaultValue(fields()[8]);
        record.instrumentId = fieldSetFlags()[9] ? this.instrumentId : (java.lang.Integer) defaultValue(fields()[9]);
        record.symbol = fieldSetFlags()[10] ? this.symbol : (java.lang.Integer) defaultValue(fields()[10]);
        record.securityType = fieldSetFlags()[11] ? this.securityType : (java.lang.Integer) defaultValue(fields()[11]);
        record.securityExchange = fieldSetFlags()[12] ? this.securityExchange : (java.lang.Integer) defaultValue(fields()[12]);
        record.side = fieldSetFlags()[13] ? this.side : (java.lang.Integer) defaultValue(fields()[13]);
        record.orderQty = fieldSetFlags()[14] ? this.orderQty : (java.lang.Integer) defaultValue(fields()[14]);
        record.ordType = fieldSetFlags()[15] ? this.ordType : (java.lang.Integer) defaultValue(fields()[15]);
        record.price = fieldSetFlags()[16] ? this.price : (java.lang.Double) defaultValue(fields()[16]);
        record.effectiveTime = fieldSetFlags()[17] ? this.effectiveTime : (java.lang.Long) defaultValue(fields()[17]);
        record.expireTime = fieldSetFlags()[18] ? this.expireTime : (java.lang.Long) defaultValue(fields()[18]);
        record.execId = fieldSetFlags()[19] ? this.execId : (java.lang.String) defaultValue(fields()[19]);
        record.orderId = fieldSetFlags()[20] ? this.orderId : (java.lang.String) defaultValue(fields()[20]);
        record.cumQty = fieldSetFlags()[21] ? this.cumQty : (java.lang.Integer) defaultValue(fields()[21]);
        record.leavesQty = fieldSetFlags()[22] ? this.leavesQty : (java.lang.Integer) defaultValue(fields()[22]);
        record.avgPrice = fieldSetFlags()[23] ? this.avgPrice : (java.lang.Double) defaultValue(fields()[23]);
        record.ordStatus = fieldSetFlags()[24] ? this.ordStatus : (java.lang.Integer) defaultValue(fields()[24]);
        record.limitAction = fieldSetFlags()[25] ? this.limitAction : (java.lang.Integer) defaultValue(fields()[25]);
        record.afterAction = fieldSetFlags()[26] ? this.afterAction : (java.lang.Integer) defaultValue(fields()[26]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Order>
    WRITER$ = (org.apache.avro.io.DatumWriter<Order>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Order>
    READER$ = (org.apache.avro.io.DatumReader<Order>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
