/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.kafang.atgo.memory.avro.record;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Balance extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -1249113792809862144L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Balance\",\"namespace\":\"com.kafang.atgo.memory.avro.record\",\"fields\":[{\"name\":\"clientId\",\"type\":\"int\"},{\"name\":\"accountId\",\"type\":\"int\"},{\"name\":\"enableBalance\",\"type\":\"double\"},{\"name\":\"creditBalance\",\"type\":\"double\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Balance> ENCODER =
      new BinaryMessageEncoder<Balance>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Balance> DECODER =
      new BinaryMessageDecoder<Balance>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<Balance> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<Balance> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Balance>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this Balance to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a Balance from a ByteBuffer. */
  public static Balance fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private int clientId;
   private int accountId;
   private double enableBalance;
   private double creditBalance;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Balance() {}

  /**
   * All-args constructor.
   * @param clientId The new value for clientId
   * @param accountId The new value for accountId
   * @param enableBalance The new value for enableBalance
   * @param creditBalance The new value for creditBalance
   */
  public Balance(java.lang.Integer clientId, java.lang.Integer accountId, java.lang.Double enableBalance, java.lang.Double creditBalance) {
    this.clientId = clientId;
    this.accountId = accountId;
    this.enableBalance = enableBalance;
    this.creditBalance = creditBalance;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return clientId;
    case 1: return accountId;
    case 2: return enableBalance;
    case 3: return creditBalance;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: clientId = (java.lang.Integer)value$; break;
    case 1: accountId = (java.lang.Integer)value$; break;
    case 2: enableBalance = (java.lang.Double)value$; break;
    case 3: creditBalance = (java.lang.Double)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'clientId' field.
   * @return The value of the 'clientId' field.
   */
  public java.lang.Integer getClientId() {
    return clientId;
  }

  /**
   * Sets the value of the 'clientId' field.
   * @param value the value to set.
   */
  public com.kafang.atgo.memory.avro.record.Balance setClientId(java.lang.Integer value) {
    this.clientId = value;
	return this;
  }

  /**
   * Gets the value of the 'accountId' field.
   * @return The value of the 'accountId' field.
   */
  public java.lang.Integer getAccountId() {
    return accountId;
  }

  /**
   * Sets the value of the 'accountId' field.
   * @param value the value to set.
   */
  public com.kafang.atgo.memory.avro.record.Balance setAccountId(java.lang.Integer value) {
    this.accountId = value;
	return this;
  }

  /**
   * Gets the value of the 'enableBalance' field.
   * @return The value of the 'enableBalance' field.
   */
  public java.lang.Double getEnableBalance() {
    return enableBalance;
  }

  /**
   * Sets the value of the 'enableBalance' field.
   * @param value the value to set.
   */
  public com.kafang.atgo.memory.avro.record.Balance setEnableBalance(java.lang.Double value) {
    this.enableBalance = value;
	return this;
  }

  /**
   * Gets the value of the 'creditBalance' field.
   * @return The value of the 'creditBalance' field.
   */
  public java.lang.Double getCreditBalance() {
    return creditBalance;
  }

  /**
   * Sets the value of the 'creditBalance' field.
   * @param value the value to set.
   */
  public com.kafang.atgo.memory.avro.record.Balance setCreditBalance(java.lang.Double value) {
    this.creditBalance = value;
	return this;
  }

  /**
   * Creates a new Balance RecordBuilder.
   * @return A new Balance RecordBuilder
   */
  public static com.kafang.atgo.memory.avro.record.Balance.Builder newBuilder() {
    return new com.kafang.atgo.memory.avro.record.Balance.Builder();
  }

  /**
   * Creates a new Balance RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Balance RecordBuilder
   */
  public static com.kafang.atgo.memory.avro.record.Balance.Builder newBuilder(com.kafang.atgo.memory.avro.record.Balance.Builder other) {
    return new com.kafang.atgo.memory.avro.record.Balance.Builder(other);
  }

  /**
   * Creates a new Balance RecordBuilder by copying an existing Balance instance.
   * @param other The existing instance to copy.
   * @return A new Balance RecordBuilder
   */
  public static com.kafang.atgo.memory.avro.record.Balance.Builder newBuilder(com.kafang.atgo.memory.avro.record.Balance other) {
    return new com.kafang.atgo.memory.avro.record.Balance.Builder(other);
  }

  /**
   * RecordBuilder for Balance instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Balance>
    implements org.apache.avro.data.RecordBuilder<Balance> {

    private int clientId;
    private int accountId;
    private double enableBalance;
    private double creditBalance;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.kafang.atgo.memory.avro.record.Balance.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.clientId)) {
        this.clientId = data().deepCopy(fields()[0].schema(), other.clientId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.accountId)) {
        this.accountId = data().deepCopy(fields()[1].schema(), other.accountId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.enableBalance)) {
        this.enableBalance = data().deepCopy(fields()[2].schema(), other.enableBalance);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.creditBalance)) {
        this.creditBalance = data().deepCopy(fields()[3].schema(), other.creditBalance);
        fieldSetFlags()[3] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Balance instance
     * @param other The existing instance to copy.
     */
    private Builder(com.kafang.atgo.memory.avro.record.Balance other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.clientId)) {
        this.clientId = data().deepCopy(fields()[0].schema(), other.clientId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.accountId)) {
        this.accountId = data().deepCopy(fields()[1].schema(), other.accountId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.enableBalance)) {
        this.enableBalance = data().deepCopy(fields()[2].schema(), other.enableBalance);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.creditBalance)) {
        this.creditBalance = data().deepCopy(fields()[3].schema(), other.creditBalance);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'clientId' field.
      * @return The value.
      */
    public java.lang.Integer getClientId() {
      return clientId;
    }

    /**
      * Sets the value of the 'clientId' field.
      * @param value The value of 'clientId'.
      * @return This builder.
      */
    public com.kafang.atgo.memory.avro.record.Balance.Builder setClientId(int value) {
      validate(fields()[0], value);
      this.clientId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'clientId' field has been set.
      * @return True if the 'clientId' field has been set, false otherwise.
      */
    public boolean hasClientId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'clientId' field.
      * @return This builder.
      */
    public com.kafang.atgo.memory.avro.record.Balance.Builder clearClientId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'accountId' field.
      * @return The value.
      */
    public java.lang.Integer getAccountId() {
      return accountId;
    }

    /**
      * Sets the value of the 'accountId' field.
      * @param value The value of 'accountId'.
      * @return This builder.
      */
    public com.kafang.atgo.memory.avro.record.Balance.Builder setAccountId(int value) {
      validate(fields()[1], value);
      this.accountId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'accountId' field has been set.
      * @return True if the 'accountId' field has been set, false otherwise.
      */
    public boolean hasAccountId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'accountId' field.
      * @return This builder.
      */
    public com.kafang.atgo.memory.avro.record.Balance.Builder clearAccountId() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'enableBalance' field.
      * @return The value.
      */
    public java.lang.Double getEnableBalance() {
      return enableBalance;
    }

    /**
      * Sets the value of the 'enableBalance' field.
      * @param value The value of 'enableBalance'.
      * @return This builder.
      */
    public com.kafang.atgo.memory.avro.record.Balance.Builder setEnableBalance(double value) {
      validate(fields()[2], value);
      this.enableBalance = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'enableBalance' field has been set.
      * @return True if the 'enableBalance' field has been set, false otherwise.
      */
    public boolean hasEnableBalance() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'enableBalance' field.
      * @return This builder.
      */
    public com.kafang.atgo.memory.avro.record.Balance.Builder clearEnableBalance() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'creditBalance' field.
      * @return The value.
      */
    public java.lang.Double getCreditBalance() {
      return creditBalance;
    }

    /**
      * Sets the value of the 'creditBalance' field.
      * @param value The value of 'creditBalance'.
      * @return This builder.
      */
    public com.kafang.atgo.memory.avro.record.Balance.Builder setCreditBalance(double value) {
      validate(fields()[3], value);
      this.creditBalance = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'creditBalance' field has been set.
      * @return True if the 'creditBalance' field has been set, false otherwise.
      */
    public boolean hasCreditBalance() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'creditBalance' field.
      * @return This builder.
      */
    public com.kafang.atgo.memory.avro.record.Balance.Builder clearCreditBalance() {
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Balance build() {
      try {
        Balance record = new Balance();
        record.clientId = fieldSetFlags()[0] ? this.clientId : (java.lang.Integer) defaultValue(fields()[0]);
        record.accountId = fieldSetFlags()[1] ? this.accountId : (java.lang.Integer) defaultValue(fields()[1]);
        record.enableBalance = fieldSetFlags()[2] ? this.enableBalance : (java.lang.Double) defaultValue(fields()[2]);
        record.creditBalance = fieldSetFlags()[3] ? this.creditBalance : (java.lang.Double) defaultValue(fields()[3]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Balance>
    WRITER$ = (org.apache.avro.io.DatumWriter<Balance>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Balance>
    READER$ = (org.apache.avro.io.DatumReader<Balance>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
